### ISSUE TITLE
Extend webpack config for `serve` command

### ISSUE THREAD

**Issue by SamVerschueren** [manfredsteyer/ngx-build-plus#1]
I always wanted to be able to use my [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin) to transpile down dependencies which use some of the new ES features. It works perfectly fine with the `build` step when using `ngx-build-plus`, would be nice if I could run it with `serve` as well.

**Comment by christianscharr** [comment]
Dont want to be rude and lure people away from here, but you may want to have a look at my recently made solution at: https://github.com/christianscharr/angular-cli-extended
It uses a similiar attempt to extend @angular/cli but also empowers you to modify the serve step and the webpack devServer configuration while running serve

**Comment by manfredsteyer** [comment]
I've implemented support for ``ng serve`` now. You find some infos about it at the end of the new readme. Also, the sample uses it in the ``serve`` script (``ng run serve``).

Can you provide me some feedback for it?
