### ISSUE TITLE
webpack output.publicPath not supported?

### ISSUE THREAD

**Issue by thescientist13** [manfredsteyer/ngx-build-plus#102]
Was trying this out to see to experiment with some of its capabilities, in particular `output` configuration.

My project is based off of a fresh Angular 7 generated CLI project.

```javascript
# webpack.partial.js
const path = require('path');
const version = require('./package.json').version;
const webpack = require('webpack');

module.exports = {

  output: {
    path: path.join(__dirname, 'public/web/my-app'),
    publicPath: 'my-app',
    hashDigest: 32
  },

  plugins: [
    new webpack.DefinePlugin({
      "VERSION": JSON.stringify(version)
    })
  ]
}
```

- The build is output in my custom directory _public/web/my-app_- ✅ 
- Hash digest works - ✅ 
- Public path is not updated in _index.html_.  Would have expected _my-app/_ to show up in the `<script>` and `<style>` paths 🚫 
```html
<link rel="stylesheet" href="styles.9047fa032743264be619.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.c64d190961200391e282.js"></script><script type="text/javascript" src="es2015-polyfills.bda95d5896422d031328.js" nomodule></script><script type="text/javascript" src="polyfills.d91e69fec887938f5ab6.js"></script><script type="text/javascript" src="main.c65bc31d07c211cc14ea.js"></script></body>
</html>
```

Thanks and let me know if you know any more info, I think this tool can definitely be a game changer for the Angular ecosystem!!  💪

**Comment by thescientist13** [comment]
Actually, it looks `outputPath` gets defined in _angular.json_ as part of the `architect` phase, so it might not be needed to "override" using this plugin.  Will take another look and report back.

**Comment by thescientist13** [comment]
Did some searching, it appears this can be done through the CLI using `--deploy-url public/static` as per https://github.com/angular/angular-cli/issues/2276#issuecomment-341372474

Doing a little more testing but might be able to close this.

**Comment by thescientist13** [comment]
Looks like `--deploy-url` is working for me, so can close this.  Thanks for great tool!  🎉

**Comment by izogfif** [comment]
`--deploy-url` is now deprecated since Angular 13. Apparently, the need to do this via ngx-build-plus arises once again.
