### ISSUE TITLE
npm run serve does not work in sample app

### ISSUE THREAD

**Issue by PsychicCat** [manfredsteyer/ngx-build-plus#11]
I tried running `npm run serve` in the sample app and get this error. Am I missing something?

```
Uncaught Error: Can't resolve all parameters for AppModule: (?).
    at syntaxError (compiler.js:1016)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:10917)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:10810)
    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10678)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:23858)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:23839)
    at JitCompiler../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:23799)
    at CompilerImpl../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:143)
    at PlatformRef../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule (core.js:4352)
    at Object../src/main.ts (main.ts:11)
```

**Comment by manfredsteyer** [comment]
Not sure. Did you resolve it?

**Comment by anddorua** [comment]
I confirm, it does now work for `ng serve`. I made small research: the **browserOptions** parameter of the **buildWebpackConfig** function inside the node_modules/ngx-build-plus/src/plus-dev-server/index.js contains **extraWebpackConfig** field which always has undefined value regardless of the parameter I provided for **ng serve --extraWebpackConfig webpack.extra.js** command. 
I don't understand why so happens. Same time **ng build** work as expected. If you could fix it it would be great. 
Here is my environment:
```
Angular CLI: 7.0.3
Node: 8.11.3
OS: linux x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

**Comment by amojicamu** [comment]
I'm having the same issue. It seems ng serve ignores all parameters. I tried --extraWebpackConfig and --single-bundle. This is pretty much a show stopper. A fix would be great.

**Comment by jmesa-sistel** [comment]
To get it working I have modified the generated /node_modules/ngx-build-plus/src/plus-dev-server/index.js

```
class PlusDevServerBuilder extends build_angular_1.DevServerBuilder {
    
    run(builderConfig) {
      this.localOptions =  builderConfig.options;
      return super.run(builderConfig);
    }
    
    buildWebpackConfig(root, projectRoot, host, browserOptions) {
    
        let config = super.buildWebpackConfig(root, projectRoot, host, browserOptions);

        if (this.localOptions.singleBundle) {
            delete config.entry.polyfills;
            delete config.entry.styles;
            delete config.optimization;
        }

        if (this.localOptions.singleBundle && browserOptions.bundleStyles !== false) {
            delete config.entry.styles;
        }

        if (this.localOptions.extraWebpackConfig) {
            const filePath = path.resolve(core_1.getSystemPath(projectRoot), this.localOptions.extraWebpackConfig);
            const additionalConfig = require(filePath);
            config = webpackMerge([config, additionalConfig]);
        }
        return config;
    }
}
```
@manfredsteyer Can you modify the lib to get the options from run(builderConfig) function?

**Comment by manfredsteyer** [comment]
Can you please retry it with the newest version. It should work now.

**Comment by igordemjanov** [comment]
It seems that after cloning a sample project it is required to update the version of "ngx build plus" in package.json, otherwise npm install return errors.

Once npm install has finished installing packages, the "serve" command is rendering a custom element without errors, but uncommenting the line that console.logs a "VERSION" in AppComponent results in the same error message as before - "Uncaught ReferenceError: VERSION is not defined".

**Comment by jmesa-sistel** [comment]
@manfredsteyer 
Is it not working for me.
Have you tested a simple sample like this ?
```
"serve": {
                    "builder": "ngx-build-plus:dev-server",
                    "options": {
                        "browserTarget": "bps:build",
                        "extraWebpackConfig": "./webpack.serve.extra.js"
                    },
                    "configurations": {
                        "production": {
                            "browserTarget": "bps:build:production"
                        }
                    }
                },
```
Now in webpack.serve.extra.js make an error to stop the build (for example one line with error word)
ng serve will work, so webpack.serve.extra.js is not processed.
Can you test my change locally? just get the options from run function.
[FIX processing options](https://github.com/manfredsteyer/ngx-build-plus/blob/82b0f6eed07c5003f57afbac2717e680dc4408cf/lib/src/plus-dev-server/index.ts)
I'll do a new clean pull request if you want , I forgot to make a branch to do the pull request so there is 2 commits instead the one needed.
