### ISSUE TITLE
incompatible peer dependency with angular 8.1.0

### ISSUE THREAD

**Issue by philjones88** [manfredsteyer/ngx-build-plus#110]
Currently on Angular CLI 8.0.6 and trying to `ng update @angular/cli` to 8.1.0 that was just released it errors with:

`Package "ngx-build-plus" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires "~0.800.0", would install "0.801.0").`

**Comment by manfredsteyer** [comment]
THX, It's solved now and we have a more relexed peerDependency on that now.
