### ISSUE TITLE
Not working in Angular 8.1.2

### ISSUE THREAD

**Issue by AgileCabaleiro** [manfredsteyer/ngx-build-plus#114]
Was working perfectly with Angular 7, after update to Angular 8.1.2 throws always same error with `ng serve` : An unhandled exception occurred: Could not find the implementation for builder ngx-build-plus:dev-server

[angular-errors.log](https://github.com/manfredsteyer/ngx-build-plus/files/3439565/angular-errors.log)

**Comment by manfredsteyer** [comment]
Thx for pointing this out. Its fixed now. Please update to the latest ngx-build-plus-version.

**Comment by AgileCabaleiro** [comment]
Thank you! Awesome work!
