### ISSUE TITLE
Cannot find the latest change log

### ISSUE THREAD

**Issue by bjornharvold** [manfredsteyer/ngx-build-plus#116]
The npm repo says there is a new version available (8.1.3) but I cannot find a change log or a release that matches this new version. 

Not sure what is in the release. Attaching what I see.

Thank you

<img width="1027" alt="Screen Shot 2019-07-31 at 2 18 53 PM" src="https://user-images.githubusercontent.com/641791/62191728-4e37df80-b39e-11e9-9625-bfa020db2921.png">

**Comment by manfredsteyer** [comment]
Thx for pointing this out. We just added Angular 8 support. I'll add an entry.
