### ISSUE TITLE
[Feature] Add BuilderConfig to Config method of the Plugin

### ISSUE THREAD

**Issue by frederikdekegel** [manfredsteyer/ngx-build-plus#118]
Could you please add the builderconfig as a parameter to the config method of the plugin? 

The builderconfig is already added to the pre and post hooks.

Example of use
I have a need to know what the target (es5, es2015, ...) is in order to determine which files I need to add to the webpack config. In order to do so I need the builderconfig.  With the builderconfig, I can determine the path of the tsConfig path and read it which will give me the target.

Thx in advance

**Comment by manfredsteyer** [comment]
Done.
