### ISSUE TITLE
build several single bundled elements

### ISSUE THREAD

**Issue by jolares** [manfredsteyer/ngx-build-plus#124]
I would like to build a library of custom elements by manually bootstrapping several components using the same angular project, and building individual single-bundle files for each element. The output within dir `/dist` would end up looking something like this:

```
+ dist/
     |- element1/
     |        |_ main-es2015.js
     |- element2/
     |       |_main-es2015.js
     | ...
```

I am sure I could get creative, but would like to know if you have a recommended approach for accomplishing this. Thanks beforehand!

**Comment by manfredsteyer** [comment]
No really. You needed to add one entry point per component via a plugin
