### ISSUE TITLE
Scss styles not bundled when --single-bundle=true

### ISSUE THREAD

**Issue by SonicGD** [manfredsteyer/ngx-build-plus#126]
Hello. I have a problem with styles when using ngx-build-plus.

Styles from `styles.scss` file is not included into final bundle when `--single-bundle=true`. `--bundle-styles=false` fixes the problem, but i don't think this is the solution. I've created example - https://github.com/SonicGD/ngbp-scss-bug.

styles.scss file:
```css
body {
    background: red;
}
```

Run with `ng serve  --extra-webpack-config webpack.partial.js` or `ng serve  --extra-webpack-config webpack.partial.js --single-bundle=true --bundle-styles=false`:

![image](https://user-images.githubusercontent.com/1222013/64152484-2973d380-ce46-11e9-9b3d-bc5ee063f8c3.png)

Run with `ng serve  --extra-webpack-config webpack.partial.js --single-bundle=true`:

![image](https://user-images.githubusercontent.com/1222013/64152414-02b59d00-ce46-11e9-8a99-a370929b4806.png)

**Comment by kelsmj** [comment]
Having the same issue.  Prevents us from bringing in material themes.

**Comment by manfredsteyer** [comment]
You can now use a new `--keepStyles` flag to get keep them.

**Comment by uzysset** [comment]
@manfredsteyer Sadly, the example repo provided by @SonicGD is still not working with ngx-build-plus 8.1.5 and --keepStyles. Am I missing something?
It seems as only the 'global' styles defined in styles.scss aren't appended to the bundle.js

**Comment by kelsmj** [comment]
Yeah, not working for me either in 8.1.5

**Comment by uzysset** [comment]
@manfredsteyer Any update?

**Comment by artu-ole** [comment]
@uzysset @kelsmj  try `--bundleStyles false --keepStyles false`. That is the only way for styles property to survive, as defaults are true for both.

https://github.com/manfredsteyer/ngx-build-plus/blob/5e0e1411d3297fb9d2a3af00f9d616ddb7d15533/lib/src/utils/index.ts#L72-L74

https://github.com/manfredsteyer/ngx-build-plus/blob/5e0e1411d3297fb9d2a3af00f9d616ddb7d15533/lib/src/browser/schema.json#L45-L55

**Comment by maciejkoch** [comment]
I have already reported it:
https://github.com/manfredsteyer/ngx-build-plus/issues/145
