### ISSUE TITLE
Single bundle still generates more than 1 JS file

### ISSUE THREAD

**Issue by alexcoroza** [manfredsteyer/ngx-build-plus#128]
I tried the `--single-bundle true` and it combines most JS files into `main.js`. This is fine but it also generates `scripts.js`, I tried to exclude it in the HTML and my app is not working. 

Is it possible to build all JS files into 1 file only? Theres also polyfills.js, I want it to be included in the generated file. The reason for this is I am creating embeddable widgets via angular-elements and I dont want the consumer to bother including 4 files(3 js, 1 css) in a page just to use my widget

**Comment by davidyoung77** [comment]
I have the same goal in my projects, to load the element by including 1 script file. I have done the following:
1. Set build configs`"keepPolyfills": true,`(in order for this to work in all browsers), `"outputHashing": "none",`(strips the hashing), `"singleBundle": true,`(combines the bundle files to 1,.
2. I then concatenate all the required js (there are 5 and the order is important) files into a single bundle file.

```javascript
concat(
      [
        `${outPath}/assets/webcomponentsjs/custom-elements-es5-adapter.js`,
        `${outPath}/polyfills-es5.js`,
        `${outPath}/polyfills.js`,
        `${outPath}/scripts.js`,
        `${outPath}/main.js`,
      ],
      `${outPath}/bundle.js`,
    );
```

I am inclined to take this a step further and handle step 2 and include logic for differential serving with custom webpack logic.

**Comment by manfredsteyer** [comment]
The important thing about single-bundle is, it creates one single self-contained bundle for your app code and all libs it uses.

It is not indended to contain scripts or polyfills b/c the consumer of your app has very likely its own. Saying this, if you get these files although, you can ignore them.

**Comment by manfredsteyer** [comment]
It's now solved.

**Comment by proto6** [comment]
I have the same issue, single bundle option generates:
```
main.js
polyfills.js
```

if I set `--keepPolyfills false` option in the build command then, polyfills.js is not being created but the app does not work, index.html is blank. This is all on a brand Ng test project.

tech stack:
```
@angular/core@9.1.11
ngx-build-plus@9.0.6
```

my full build command:
`ng build --single-bundle true --bundle-styles true --keep-styles true --keepPolyfills false --prod --output-hashing=none`

Thanks.
