### ISSUE TITLE
Polyfill for IE11 to support encapsulation: ViewEncapsulation.ShadowDom in Angular8+

### ISSUE THREAD

**Issue by ringodotnl** [manfredsteyer/ngx-build-plus#129]
What is the polyfill setup to support IE11 with Angular 8+ so one can use:
encapsulation: ViewEncapsulation.ShadowDom  ?

Cheers,
Ringo.

**Comment by manfredsteyer** [comment]
This one would work: https://www.webcomponents.org/polyfills

However, to make everything work correctly, you need to add the script-tag after the script-tag for pollyfills in your index.html
