### ISSUE TITLE
ERROR in No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by LoganDark** [manfredsteyer/ngx-build-plus#13]
![image](https://user-images.githubusercontent.com/4723091/44953350-fb317180-ae48-11e8-8e4c-724cb979f163.png)

You'll notice something here that is completely present.

![image](https://user-images.githubusercontent.com/4723091/44953359-4b103880-ae49-11e8-80ee-f2c6495e52d5.png)

Imported from `@angular/core`, of course...

This is a completely blank, unmodified Angular CLI project. It uses `ngx-build-plus`'s build system, but it seems like Angular's upset about something.

I haven't modified anything aside from removing Angular's testing bloat and e2e nonsense, as well as installing this particular package.

**Comment by LoganDark** [comment]
...................what the fuck

`touch src/app/app.module.ts` -> successful build

I have to do this every time I run `ng serve` (and keep it running in the meantime), but apparently it needs two tries to get it right.

**Comment by vagostep** [comment]
I have the same bug.

**Comment by vagostep** [comment]
reopen!!

**Comment by LoganDark** [comment]
@vagostep Solution: Don't use ngx-build-plus, it doesn't work anymore.

**Comment by vagostep** [comment]
I find the problem. We put de ngx-build-plus as builder in the principal app. We need only in the projects that need build into one file.
