### ISSUE TITLE
Suggestion to restructure some property names and logic

### ISSUE THREAD

**Issue by BioPhoton** [manfredsteyer/ngx-build-plus#130]
# Motivation
As the properties `--singleBundle` implies it is here to produce a single bundle.
At the moment some flags are IMHO unintuitive.  as described in  Actual Behaviour. 

The goal would be to have a consistent and intuitive list of properties.

**Note For Reader:**
The actual list of properties can be found in [schema.json](https://github.com/manfredsteyer/ngx-build-plus/blob/ec4a46bfee38bdc3c9731ba4a5e06020d3e48d65/lib/src/plus/schema.json#L23)

# Actual Behaviour
When using `--singleBundle` default the following files get bundled:
- vendor-es2015.js
- main-es2015.js
- runtime-es2015.js

The output file is named `main-es2015.js`.

With some of the provided properties, you could change the output of a build.
In particular we speak about following properties: 
- `--keepPolyfills`  (`false` by default)
- `--bundleStyles` (`true` by default)

## Property `keepPolyfills`
When used as `--singleBundle --keepPolyfills` it produces the following bundles:
- main-es2015.js
- polyfills-es2015.js

We can then combine those 2 files in a separate step to have our single bundle for .i.e stand-alone usage.

## Property `bundleStyles`
When used as `--singleBundle --bundleStyles false` it produces the following bundles:
- main-es2015.js
- styles-es2015.js

We can then combine those 2 files in a separate step to have our single bundle for .i.e stand-alone usage.

Here it was unintuitive for me to understand the intention of the flag, as I assumed it will bundle the styles into the main-es2015.js and not keep them as it is the case with `--keepPolyfills`

# Suggested Change
When using `--singleBundle` i suggest the following adoptions:

Delete the following properties:
- `--keepPolyfills` 
- `--bundleStyles` 

Implement following properties
- `--include <file-name>` (`''` by default)
- `--splice <file-name>` (`''` by default)
Optional:
- `--includePolyfills` (`false` by default)
- `--includeStyles` (`false` by default)
- `--spliceZone` (`false` by default)

## Properties `include`
Name: **include**
Type: **String**
Default: **''**
Usage **`--singleBundle --include file-name other-file-name`**

When used as `--singleBundle --include polyfills-es2015.js styles-es2015.js` it bundles following files in order :
- vendor-es2015.js
- main-es2015.js
- runtime-es2015.js
- polyfills-es2015.js
- styles-es2015.js

and name the output `main-es2015.js`.

We now have a single bundle that can easily be used for .i.e stand-alone usage.
Because of we can reference any file in the`dist` folder and we can order them we have and easy way to fully control our bundle.

## Properties `splice`
Name: **splice**
Type: **String**
Default: **''**
Usage **`--singleBundle --splice file-name other-file-name`**

When used as `--singleBundle --splice zone.js` it bundles following files:
- vendor-es2015.js
- main-es2015.js
- runtime-es2015.js
and name the output `main-es2015.js`.

In addition, another separate bundle named `zone.js` gets created with following files included:
- zone.js

**Why is a separate `zone.js` bundle this important?**
If we can splice `zone.js` over the build process and not by providing a separate `polyfill.zone-less.ts` it would make the project only depend on the configuration and no code adoptions. (no difference in the file names)

---

With the 2 new properties `include` and `include` we now have a single bundle that can easily be used for .i.e stand-alone usage.
Because we can reference any file in the`dist` folder and we can order them we have an easy way to fully control our bundle.

---

## Optional Property `includePolyfills`
Name: **includePolyfills**
Type: **Boolean**
Default: **false**
Usage **`--singleBundle --includePolyfills`**

When used as `--singleBundle --includePolyfills` it bundles following files:
- main-es2015.js
- polyfills-es2015.js

and name the output `main-es2015.js`.

## Optional Property `includeStyles`
Name: **includeStyles**
Type: **Boolean**
Default: **false**
Usage **`--singleBundle --includeStyles`**

When used as `--singleBundle --includeStyles` it bundles following files:
- main-es2015.js
- styles-es2015.js

and name the output `main-es2015.js`.

We now have a single bundle that can easily be used for .i.e stand-alone usage.

## Optional Property `spliceZone`
Name: **spliceZone**
Type: **Boolean**
Default: **false**
Usage **`--singleBundle --spliceZone`**

When used as `--singleBundle --spliceZone` it produces the following bundles:
- main-es2015.js
- zone.js

We now have a single bundle that can easily be used for .i.e stand-alone usage.

**Comment by BioPhoton** [comment]
Found related comment: https://github.com/manfredsteyer/ngx-build-plus/issues/4#issuecomment-407742673

**Comment by manfredsteyer** [comment]
Thanks for this.

Just added `keepStyles` for parity with `keepPolyfills`. 

For the rest, I would suggest to write a plugin.

If your plugin delegates to several helper functions for the outlined aspects, we could open source them here via a `ngrx-build-plus/contrib` module.
