### ISSUE TITLE
error occurred in angular-cli8.3.5

### ISSUE THREAD

**Issue by gtjyj** [manfredsteyer/ngx-build-plus#133]
in angular-cli version 8.3.5, when i use option "ng build --prod",  one error occured:

> Schema validation failed with the following errors:
  Data path ".budgets[1].type" should be equal to one of the allowed values.

when i change the angular.json from  "builder": "ngx-build-plus:build"  to "builder": "@angular-devkit/build-angular:browser" , all will be sucess.

after the error, i rollback the cli version from 8.3.5 to 8.0.2，all working  expected

**Comment by ringodotnl** [comment]
FYI no erorr using cli version 8.3.0.

**Comment by moefinley** [comment]
I get the error on version 8.3.5, 8.3.0 and 8.0.2

`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ivy-web-component-test": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "ngx-build-plus:browser",
          "options": {
            "outputPath": "dist/ivy-web-component-test",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "ngx-build-plus:dev-server",
          "options": {
            "browserTarget": "ivy-web-component-test:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "ivy-web-component-test:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "ivy-web-component-test:build"
          }
        },
        "test": {
          "builder": "ngx-build-plus:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "ivy-web-component-test:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "ivy-web-component-test:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "ivy-web-component-test"
}`

**Comment by itmuckel** [comment]
To expand @moefinley's answer.
In `angular.json` remove:
```js
{
"type": "anyComponentStyle",
"maximumWarning": "6kb",
"maximumError": "10kb"
}
```

**Comment by artu-ole** [comment]
This is not a resolved issue unless [schema.json](https://github.com/manfredsteyer/ngx-build-plus/blob/cli8/lib/src/browser/schema.json) actually gets updated to reflect changes in [angular_devkit/build_angular/src/browser/schema.json](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/browser/schema.json)

**Comment by laurencefass** [comment]
removing 

`{
"type": "anyComponentStyle",
"maximumWarning": "6kb",
"maximumError": "10kb"
}
`

allows a universal build to proceed. can anyone explain the issue in greater detail?

thanks

**Comment by Maistho** [comment]
I opened #158 which should fix this.
