### ISSUE TITLE
Split Web Components?

### ISSUE THREAD

**Issue by itmuckel** [manfredsteyer/ngx-build-plus#134]
I have an angular application that registers two web components. Is it possible to compile them into separate files?

Use Case:
I want to build separate web components that will be loaded when needed, but have the same dependencies. They live in the same project, but they probably never end up on the same page.

In the current state I'd need to remove all components/subcomponents from one web component and include all components/subcomponents from the other web component to have them compile to separate files. OR keep different projects.

Is there a solution to this?

**Comment by manfredsteyer** [comment]
We needed two seperate entry points, bootstrapping an angular app with the web component in question. You can do this with a plugin.
