### ISSUE TITLE
Angular 9 support ?

### ISSUE THREAD

**Issue by ringodotnl** [manfredsteyer/ngx-build-plus#139]
When will you support Angular 9 ?

Cheers,
Ringo.

**Comment by ringodotnl** [comment]
Cheers, will test this in the coming weeks and report it here.

**Comment by BrainMaxxx** [comment]
@manfredsteyer  A couple of my projects fails to build cause of:
_An unhandled exception occurred: context.getProjectMetadata is not a function_

The log pointing to _i18n-options.js_ inside _@angular-devkit/build-angular_, line 70

And, by the way, I am not using standart angular's i18n

**Comment by manfredsteyer** [comment]
Can you show me your package.json?

**Comment by BrainMaxxx** [comment]
@manfredsteyer here it is:
{
  "name": "oc-web-app",
  "version": "0.0.5",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "npm run build:worker && ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
  },
  "dependencies": {
    "@angular/animations": "9.0.0-rc.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "9.0.0-rc.0",
    "@angular/compiler": "9.0.0-rc.0",
    "@angular/core": "9.0.0-rc.0",
    "@angular/elements": "9.0.0-rc.0",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "9.0.0-rc.0",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "9.0.0-rc.0",
    "@angular/platform-browser-dynamic": "9.0.0-rc.0",
    "@angular/pwa": "^0.800.3",
    "@angular/router": "9.0.0-rc.0",
    "@angular/service-worker": "9.0.0-rc.0",
    "@aspnet/signalr": "^1.1.4",
    "@babel/polyfill": "^7.4.4",
    "@babel/runtime": "^7.4.5",
    "@clr/icons": "^2.2.0",
    "@ctrl/ngx-headroom": "^2.3.2",
    "@datorama/akita": "^4.10.2",
    "@fortawesome/fontawesome-free": "^5.9.0",
    "@ng-bootstrap/ng-bootstrap": "^5.1.1",
    "@ngneat/transloco": "^2.3.1",
    "@ngui/map": "^0.30.3",
    "@swimlane/dragula": "^3.8.0",
    "@swimlane/ngx-datatable": "^16.0.2",
    "@swimlane/ngx-dnd": "^8.0.0",
    "@webcomponents/custom-elements": "^1.2.4",
    "@webcomponents/template": "^1.4.0",
    "angular-gridster2": "^8.0.0",
    "angular-tree-component": "^8.4.0",
    "angular2-text-mask": "^9.0.0",
    "angular2-toaster": "7.0.0",
    "babel-plugin-transform-es2015-constants": "^6.1.4",
    "bootstrap": "^4.3.1",
    "browser-detect": "0.2.28",
    "classlist.js": "^1.1.20150312",
    "comlink": "^4.1.0",
    "core-js": "^3.1.4",
    "countup.js-angular2": "^7.3.0",
    "d3": "^5.9.2",
    "dayjs": "^1.8.14",
    "document-register-element": "^1.13.2",
    "echarts": "^4.2.1",
    "fast-deep-equal": "^2.0.1",
    "fastdom": "^1.0.9",
    "firebase": "^6.2.2",
    "grapesjs": "0.14.62",
    "grapesjs-blocks-basic": "0.1.8",
    "grapesjs-component-countdown": "0.1.3",
    "grapesjs-custom-code": "^0.1.2",
    "grapesjs-navbar": "0.1.5",
    "grapesjs-plugin-export": "^1.0.5",
    "grapesjs-plugin-filestack": "^0.1.1",
    "grapesjs-plugin-forms": "1.0.5",
    "hammerjs": "^2.0.8",
    "https": "^1.0.0",
    "imagesloaded": "^4.1.4",
    "immer": "^3.1.3",
    "immutable": "4.0.0-rc.12",
    "intersection-observer": "^0.7.0",
    "isotope-layout": "^3.0.6",
    "jquery-lite": "2.2.3",
    "juice": "^5.2.0",
    "linq": "^3.2.0",
    "lit-html": "^1.1.0",
    "mandrill-api": "^1.0.45",
    "masonry-layout": "^4.2.2",
    "memoizee": "^0.4.14",
    "memorize-decorator": "^0.2.1",
    "monaco-editor": "^0.17.1",
    "ng-animate": "^0.3.4",
    "ng-dynamic-component": "^4.0.3",
    "ng-in-viewport": "^6.0.3",
    "ng2-cache": "0.2.1",
    "ng2-tooltip-directive": "^2.8.17",
    "ngc": "^1.0.0",
    "ngx-bootstrap": "^5.2.0",
    "ngx-echarts": "^4.2.1",
    "ngx-filter-pipe": "^2.1.2",
    "ngx-isotope": "^0.1.7",
    "ngx-loadable": "^1.0.10",
    "ngx-monaco-editor": "^7.0.0",
    "ngx-perfect-scrollbar": "^8.0.0",
    "ngx-quicklink": "^0.1.0",
    "ngx-quill": "^6.0.1",
    "ngx-scrollbar": "^4.2.0",
    "ngx-scrollreveal": "^3.0.0",
    "ngx-swiper-wrapper": "^8.0.0",
    "ngx-ui-loader": "8.0.0",
    "node": "^12.4.0",
    "node-sass-json-importer": "^4.1.0",
    "path": "^0.12.7",
    "popper.js": "^1.15.0",
    "quill": "^1.3.6",
    "replace-in-file-webpack-plugin": "^1.0.6",
    "rickshaw": "^1.6.6",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.2",
    "scrollreveal": "^4.0.5",
    "scss-to-json": "^2.0.0",
    "simple-keyboard": "^2.26.4",
    "socket.io-client": "^2.1.1",
    "split.js": "1.5.11",
    "stacktrace-js": "^2.0.0",
    "text-mask-addons": "^3.8.0",
    "tiny-slider": "^2.9.2",
    "ts-loader": "^6.0.4",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^8.2.0",
    "@angular-builders/dev-server": "^7.3.1",
    "@angular-devkit/architect": "^0.800.3",
    "@angular-devkit/build-angular": "^0.900.0-rc.0",
    "@angular-devkit/build-ng-packagr": "^0.900.0-rc.0",
    "@angular/cli": "9.0.0-rc.0",
    "@angular/compiler-cli": "9.0.0-rc.0",
    "@angular/language-service": "9.0.0-rc.0",
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-transform-arrow-functions": "^7.2.0",
    "@babel/plugin-transform-classes": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-typescript": "^7.3.3",
    "@compodoc/compodoc": "^1.1.9",
    "@datorama/akita-ngdevtools": "^3.0.2",
    "@ngneat/transloco-optimize": "^1.0.1",
    "@phenomnomnominal/angular-lazy-routes-fix": "^0.1.5",
    "@types/d3": "^5.7.2",
    "@types/google.analytics": "^0.0.40",
    "@types/googlemaps": "^3.36.5",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "~2.0.3",
    "@types/memoizee": "^0.4.2",
    "@types/node": "^12.0.10",
    "@types/scrollreveal": "0.0.4",
    "@types/socket.io": "^2.1.0",
    "@types/socket.io-client": "^1.4.32",
    "@types/stacktrace-js": "0.0.32",
    "@webcomponents/webcomponentsjs": "2.2.10",
    "babel-loader": "^8.0.6",
    "babel-plugin-transform-es2015-block-scoping": "^6.26.0",
    "babel-plugin-transform-es2015-template-literals": "^6.22.0",
    "codelyzer": "^5.1.0",
    "http-server": "^0.11.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ng-packagr": "9.0.0-rc.1",
    "ng-swagger-gen": "1.7.0-b",
    "ngx-build-plus": "^9.0.2",
    "node-sass": "^4.12.0",
    "perfume.js": "^2.1.2",
    "prettier": "^1.18.2",
    "pretty-quick": "^1.11.1",
    "protractor": "^5.4.1",
    "reflect-metadata": "0.1.13",
    "replace-in-file": "^4.1.1",
    "ts-node": "~8.3.0",
    "tsickle": "^0.35.0",
    "tslib": "^1.10.0",
    "tslint": "~5.18.0",
    "typescript": "3.6.4",
    "webpack-bundle-analyzer": "3.3.2",
    "webpack-dev-server": "^3.7.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  }
}

**Comment by ringodotnl** [comment]
Tested it with NG 9 version next 16, no problems there. 
Will test with ng 9 RC0 soon.

**Comment by ringodotnl** [comment]
Tested with RC0 and RC1 do get error:

Uncaught NullInjectorError: StaticInjectorError(Platform: core)[Em]: 
  NullInjectorError: No provider for Em!
 
Will try to figure this out.

**Comment by ringodotnl** [comment]
Updated the sample directory to **NG9 RC1** with the package.json below.

Did build the project (npm run build) and tried to run it and getting the following error:

scripts.e7fd3f0ed405f69aaeec.js:1 Uncaught NullInjectorError: StaticInjectorError(Platform: core)[Ig]: 
  NullInjectorError: No provider for Ig!
    at e.get (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:133311)
    at http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:217054
    at t (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:217473)
    at t.get (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:217600)
    at http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:334170
    at e.bootstrapModule (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:334220)
    at Module.zUnb (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:1943)
    at n (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:110)
    at Object.0 (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:943)
    at n (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:110)

sample dir new package.json content (for NG RC1):

`{
  "name": "elements-loading",
  "version": "0.0.0",
  "scripts": {
    "start": "ng serve --extra-webpack-config webpack.serve.extra.js  -o",
    "build": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod",
    "start:prod": "live-server dist/elements-loading",
    "build:modern": "ng build --plugin ngx-build-modern --project empty-demo --prod",
    "build:plugin": "tsc hook/modern-plugin --module commonjs --target es5 --lib DOM,ES6,ScriptHost && ng build --plugin ~hook/modern-plugin",
    "build:test": "tsc test.ts --module commonjs --target es5 --lib DOM,ES6,ScriptHost && node test.js",
    "build:externals": "ng build --extra-webpack-config webpack.externals.js --prod --single-bundle",
    "start:externals": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true -o",
    "build:externals:empty-demo": "ng build --extra-webpack-config webpack.externals.js --prod --project empty-demo",
    "start:externals:empty-demo": "ng serve --extra-webpack-config webpack.externals.js --project empty-demo",
    "build:externals:elements-loading": "ng build --extra-webpack-config webpack.externals.js --prod --project elements-loading",
    "start:externals:elements-loading": "ng serve --extra-webpack-config webpack.externals.js --project elements-loading",
    "build:old": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod",
    "start:old": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true -o",
    "build:elements-loading": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project elements-loading",
    "start:elements-loading": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true --project elements-loading -o",
    "npx-build-plus:copy-assets": "node projects/externals-demo/copy-wc-polyfill.js && node copy-wc-polyfill.js && node copy-bundles.js && node projects/externals-demo/copy-bundles.js && node projects/delme1/copy-bundles.js && node projects/delme1-host/copy-bundles.js && node projects/delme2-host/copy-bundles.js && node projects/delme2/copy-bundles.js && node projects/empty-demo/copy-wc-polyfill.js && node projects/externals-demo-scripts//copy-wc-polyfill.js",
    "build:externals-demo": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project externals-demo",
    "start:externals-demo": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true --project externals-demo -o",
    "build:delme1:externals": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project delme1",
    "build:delme1-host:externals": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project delme1-host",
    "build:delme2-host:externals": "ng build --extra-webpack-config webpack.externals.js  --prod --project delme2-host",
    "build:delme2:externals": "ng build --extra-webpack-config webpack.externals.js -- single-bundle --output-hashing none --prod --project delme2",
    "build:elements-loading:externals": "ng build --extra-webpack-config webpack.externals.js --prod --project elements-loading --single-bundle",
    "build:externals-demo-scripts:externals": "ng build --extra-webpack-config projects/externals-demo-scripts/webpack.externals.js --prod --project externals-demo-scripts --single-bundle"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "9.0.0-rc.1",
    "@angular/common": "9.0.0-rc.1",
    "@angular/compiler": "9.0.0-rc.1",
    "@angular/core": "9.0.0-rc.1",
    "@angular/elements": "9.0.0-rc.1",
    "@angular/forms": "9.0.0-rc.1",
    "@angular/platform-browser": "9.0.0-rc.1",
    "@angular/platform-browser-dynamic": "9.0.0-rc.1",
    "@angular/router": "9.0.0-rc.1",
    "@webcomponents/webcomponentsjs": "^2.3.0",
    "app": "^0.1.0",
    "copy": "^0.3.2",
    "core-js": "^3.4.0",
    "document-register-element": "^1.14.3",
    "domino": "^2.1.3",
    "ngx-build-modern": "^1.1.10",
    "rxjs": "^6.5.3",
    "tslib": "^1.9.3",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.900.0-rc.0",
    "@angular/cli": "9.0.0-rc.0",
    "@angular/compiler-cli": "9.0.0-rc.1",
    "@angular/language-service": "9.0.0-rc.1",
    "@angular-devkit/build-ng-packagr": "~0.803.17",
    "@types/jasmine": "~3.4.6",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~12.12.6",
    "codelyzer": "^5.2.0",
    "cpr": "^3.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "live-server": "^1.2.1",
    "ng-packagr": "^5.7.1",
    "ngx-build-plus": "",
    "protractor": "^5.4.2",
    "ts-node": "~8.4.1",
    "tsickle": ">=0.37.1",
    "tslib": "^1.10.0",
    "tslint": "~5.20.1",
    "typescript": "3.6.4",
    "webpack-cli": "^3.3.10"
  }
}
`

**Comment by ringodotnl** [comment]
When removing:
              "node_modules/rxjs/bundles/rxjs.umd.js",
              "node_modules/@angular/core/bundles/core.umd.js",
              "node_modules/@angular/common/bundles/common.umd.js",
              "node_modules/@angular/common/bundles/common-http.umd.js",
              "node_modules/@angular/compiler/bundles/compiler.umd.js",
              "node_modules/@angular/elements/bundles/elements.umd.js",
              "node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
              "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"

from angular.json and removing:

    rxjs: 'rxjs',
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    '@angular/common/http': 'ng.common.http',
    '@angular/platform-browser': 'ng.platformBrowser',
    '@angular/platform-browser-dynamic': 'ng.platformBrowserDynamic',
    '@angular/compiler': 'ng.compiler',
    '@angular/elements': 'ng.elements',
    '@angular/router': 'ng.router',
    '@angular/forms': 'ng.forms'

from webpack.externals.js it works.

Any idea how to fix this ?

**Comment by ringodotnl** [comment]
Did try ng9 rc2 still same problem as above.

**Comment by ringodotnl** [comment]
testen with NG9 RC2 still the same issue, anyone ?

**Comment by ringodotnl** [comment]
We reverted to ng8 for now.

**Comment by tommck** [comment]
> "@babel/polyfill": "^7.4.4",
> "@babel/runtime": "^7.4.5",

@BrainMaxxx how are you using babel with the CLI?  I'm dying to know!

**Comment by chetbis** [comment]
> Updated the sample directory to **NG9 RC1** with the package.json below.
> 
> Did build the project (npm run build) and tried to run it and getting the following **error**:
> 
> scripts.e7fd3f0ed405f69aaeec.js:1 Uncaught NullInjectorError: StaticInjectorError(Platform: core)[Ig]:
> NullInjectorError: No provider for Ig!
> at e.get (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:133311)
> at http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:217054
> at t (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:217473)
> at t.get (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:217600)
> at http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:334170
> at e.bootstrapModule (http://127.0.0.1:5501/sample/dist/elements-loading/scripts.e7fd3f0ed405f69aaeec.js:1:334220)
> at Module.zUnb (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:1943)
> at n (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:110)
> at Object.0 (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:943)
> at n (http://127.0.0.1:5501/sample/dist/elements-loading/main.74e7319bacefd10fa1cf.js:1:110)
> 
> Any idea how to fix that ?
> 
> sample dir new package.json content (for NG RC1):
> 
> `{
> "name": "elements-loading",
> "version": "0.0.0",
> "scripts": {
> "start": "ng serve --extra-webpack-config webpack.serve.extra.js -o",
> "build": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod",
> "start:prod": "live-server dist/elements-loading",
> "build:modern": "ng build --plugin ngx-build-modern --project empty-demo --prod",
> "build:plugin": "tsc hook/modern-plugin --module commonjs --target es5 --lib DOM,ES6,ScriptHost && ng build --plugin ~hook/modern-plugin",
> "build:test": "tsc test.ts --module commonjs --target es5 --lib DOM,ES6,ScriptHost && node test.js",
> "build:externals": "ng build --extra-webpack-config webpack.externals.js --prod --single-bundle",
> "start:externals": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true -o",
> "build:externals:empty-demo": "ng build --extra-webpack-config webpack.externals.js --prod --project empty-demo",
> "start:externals:empty-demo": "ng serve --extra-webpack-config webpack.externals.js --project empty-demo",
> "build:externals:elements-loading": "ng build --extra-webpack-config webpack.externals.js --prod --project elements-loading",
> "start:externals:elements-loading": "ng serve --extra-webpack-config webpack.externals.js --project elements-loading",
> "build:old": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod",
> "start:old": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true -o",
> "build:elements-loading": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project elements-loading",
> "start:elements-loading": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true --project elements-loading -o",
> "npx-build-plus:copy-assets": "node projects/externals-demo/copy-wc-polyfill.js && node copy-wc-polyfill.js && node copy-bundles.js && node projects/externals-demo/copy-bundles.js && node projects/delme1/copy-bundles.js && node projects/delme1-host/copy-bundles.js && node projects/delme2-host/copy-bundles.js && node projects/delme2/copy-bundles.js && node projects/empty-demo/copy-wc-polyfill.js && node projects/externals-demo-scripts//copy-wc-polyfill.js",
> "build:externals-demo": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project externals-demo",
> "start:externals-demo": "ng serve --extra-webpack-config webpack.externals.js --single-bundle true --project externals-demo -o",
> "build:delme1:externals": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project delme1",
> "build:delme1-host:externals": "ng build --extra-webpack-config webpack.externals.js --single-bundle true --prod --project delme1-host",
> "build:delme2-host:externals": "ng build --extra-webpack-config webpack.externals.js --prod --project delme2-host",
> "build:delme2:externals": "ng build --extra-webpack-config webpack.externals.js -- single-bundle --output-hashing none --prod --project delme2",
> "build:elements-loading:externals": "ng build --extra-webpack-config webpack.externals.js --prod --project elements-loading --single-bundle",
> "build:externals-demo-scripts:externals": "ng build --extra-webpack-config projects/externals-demo-scripts/webpack.externals.js --prod --project externals-demo-scripts --single-bundle"
> },
> "private": true,
> "dependencies": {
> "@angular/animations": "9.0.0-rc.1",
> "@angular/common": "9.0.0-rc.1",
> "@angular/compiler": "9.0.0-rc.1",
> "@angular/core": "9.0.0-rc.1",
> "@angular/elements": "9.0.0-rc.1",
> "@angular/forms": "9.0.0-rc.1",
> "@angular/platform-browser": "9.0.0-rc.1",
> "@angular/platform-browser-dynamic": "9.0.0-rc.1",
> "@angular/router": "9.0.0-rc.1",
> "@webcomponents/webcomponentsjs": "^2.3.0",
> "app": "^0.1.0",
> "copy": "^0.3.2",
> "core-js": "^3.4.0",
> "document-register-element": "^1.14.3",
> "domino": "^2.1.3",
> "ngx-build-modern": "^1.1.10",
> "rxjs": "^6.5.3",
> "tslib": "^1.9.3",
> "zone.js": "^0.10.2"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "0.900.0-rc.1",
> "@angular-devkit/build-ng-packagr": "0.900.0-rc.1",
> "@angular-devkit/build-angular": "0.900.0-rc.1",
> "@angular/cli": "9.0.0-rc.1",
> "@angular/compiler-cli": "9.0.0-rc.1",
> "@angular/language-service": "9.0.0-rc.1",
> "@angular-devkit/build-ng-packagr": "0.900.0-rc.1",
> "@types/jasmine": "~3.4.6",
> "@types/jasminewd2": "~2.0.8",
> "@types/node": "~12.12.6",
> "codelyzer": "^5.2.0",
> "cpr": "^3.0.1",
> "jasmine-core": "~3.5.0",
> "jasmine-spec-reporter": "~4.2.1",
> "karma": "~4.4.1",
> "karma-chrome-launcher": "~3.1.0",
> "karma-coverage-istanbul-reporter": "~2.1.0",
> "karma-jasmine": "~2.0.1",
> "karma-jasmine-html-reporter": "^1.4.2",
> "live-server": "^1.2.1",
> "ng-packagr": "^5.7.1",
> "ngx-build-plus": "",
> "protractor": "^5.4.2",
> "ts-node": "~8.4.1",
> "tsickle": ">=0.37.1",
> "tslib": "^1.10.0",
> "tslint": "~5.20.1",
> "typescript": "3.6.4",
> "webpack-cli": "^3.3.10"
> }
> }
> ``

I am getting the same issue with angular 9

**Comment by ringodotnl** [comment]
It's working with ng9 and projects now.

**Comment by pyrchJ** [comment]
I get this error in Angular 9: An unhandled exception occurred: Script file node_modules/@angular/elements/bundles/elements.umd.js does not exist.
