### ISSUE TITLE
"ng serve --single-bundle --open" shows blank page with angular 8.3 and ngx-build-plus 8.1.5

### ISSUE THREAD

**Issue by lihaostar** [manfredsteyer/ngx-build-plus#143]
ng new myapp
cd myapp
ng add ngx-build-plus
ng serve --open shows the default angular page correctly. 
ng serve --single-bundle --open loads everything without any error but the page is blank.

Not sure if this is expected or not. And how can I get it work with single-bundle enabled?

thanks.

**Comment by manfredsteyer** [comment]
Please try to add --keep-polyfills and --keep-styles.

The original idea of --single-bundle was to create a single bundle we can ship to a consuming application which has its own polyfills .
