### ISSUE TITLE
Both BundleStyles and keepStyles must be set 

### ISSUE THREAD

**Issue by maciejkoch** [manfredsteyer/ngx-build-plus#145]
Is the condition for bundleStyles and keepStyles correct? Both by default are set as true so you have to set both as false to avoid deleting entry styles.

https://github.com/manfredsteyer/ngx-build-plus/blob/cli8/lib/src/utils/index.ts
``` js
if (options.singleBundle && (options.bundleStyles !== false || options.keepStyles) && config.entry && config.entry['styles']) {
  delete config.entry['styles'];
}
```

**Comment by manfredsteyer** [comment]
Good point.

**Comment by kessenich** [comment]
Can we remove the deprecated `bundleStyles`? 
Else I don't have an idea to fix the issue. Maybe make it better, that it works with the default values `!(options.bundleStyles || options.keepStyles)`. But than for deleting the styles both options must be false (so the opposite we have).

I have seen, that the schema.json's have all default properties from Angular. With the new angular_devkit and Angular 8 Builders, we can combine the schemas in the `createBuilder` Method. Would maybe nice for maintenance.

**Comment by hisham** [comment]
I tried setting both variables to false but I am getting the following in angular/cli 9.0.3: 

Further investigation shows 'filename' is a function and so does not have endsWith method. 

```
ng build --prod --output-hashing none --single-bundle --bundle-styles=false --keep-styles=false  

ERROR in chunk styles [entry]
({
              chunk: chunkData
            }) => this.options.moduleFilename(chunkData)
filename.endsWith is not a function
TypeError: filename.endsWith is not a function
    at <redact>/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:108:72
    at SyncWaterfallHook.eval [as call] (eval at create (<redact>/frontend/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at MainTemplate.getAssetPathWithInfo (<redact>/frontend/node_modules/webpack/lib/MainTemplate.js:527:40)
    at Compilation.getPathWithInfo (/Users/hisham/src/ess-app/frontend/node_modules/webpack/lib/Compilation.js:2227:28)
    at Compilation.createChunkAssets (<redact>/node_modules/webpack/lib/Compilation.js:2138:31)
 ...
```

**Comment by hisham** [comment]
I filed https://github.com/angular/angular-cli/issues/17087 for the fileName.endsWith issue.
