### ISSUE TITLE
ngx-build-plus with @angular/localize

### ISSUE THREAD

**Issue by DmitriyIvanko** [manfredsteyer/ngx-build-plus#160]
Feature request or doc:
If run command:
ng build --prod --localize
Ngx-build-plus does not place the output in a locale-specific directory to keep it separate from other locale versions of application.
But original CLI does:  https://next.angular.io/guide/i18n
How can I place the output in a locale-specific directory by ngx-build-plus?

"@angular/localize": "~9.0.0-rc.8",
"ngx-build-plus": "^9.0.2",

**Comment by manfredsteyer** [comment]
Can you pls retry this with ``ngx-build-plus`` version ``9.0.6``.

Does this work for you?

**Comment by DmitriyIvanko** [comment]
@manfredsteyer sorry, for slow response. It's works properly with version 9.0.6.
