### ISSUE TITLE
builderConfig.options doesn't exist anymore

### ISSUE THREAD

**Issue by maxisam** [manfredsteyer/ngx-build-plus#161]
Just update from 7 to 9.

It shows error like 

> An unhandled exception occurred: Cannot read property 'outputPath' of undefined

I traced it back to `post(builderConfig)` 
https://github.com/manfredsteyer/ngx-build-plus/blob/b2871c390ec61bf3afcf76d5fc499e1ebd109a99/sample/hook/modern-plugin.ts#L48

somehow the items under builderConfig.options are all under builderConfig now

**Comment by manfredsteyer** [comment]
Beginning with version 8, the ``modern-plugin`` is not supported anymore b/c the CLI comes now with built-in support for differential loading.

**Comment by maxisam** [comment]
But this issue is not about modern-plugin.

It is about the items under `options` are moved to `buildConfig` instead of the original structure.
