### ISSUE TITLE
Angular.json Schema has a validation issue in ngx-build-plus

### ISSUE THREAD

**Issue by JoeFirebaugh** [manfredsteyer/ngx-build-plus#173]
# 🐞 Bug report

### Is this a regression?

Yes, this worked with Angular CLI 8.2.3

### Description

```
 "styles": [
              "src/styles.scss",
              "./node_modules/codemirror/lib/codemirror.css",
              "./node_modules/codemirror/theme/ambiance.css",
              {
                "input": "src/themes/light/LightTheme.scss",
                "inject": false,
                "bundleName": "LightTheme",
              },
              {
                "input": "src/themes/slate/SlateTheme.scss",
                "inject": false,
                "bundleName": "SlateTheme",
              }
            ],
```
Using the above for styles I get the following error:
`Data path ".styles[3]" should NOT have additional properties(inject).`

The schema says that is valid (and incidentally Webstorm confirms):
```
"extraEntryPoint": {
              "oneOf": [
                {
                  "type": "object",
                  "properties": {
                    "input": {
                      "type": "string",
                      "description": "The file to include."
                    },
                    "bundleName": {
                      "type": "string",
                      "description": "The bundle name for this extra entry point."
                    },
                    "lazy": {
                      "type": "boolean",
                      "description": "If the bundle will be lazy loaded.",
                      "default": false
                    },
                    "inject": {
                      "type": "boolean",
                      "description": "If the bundle will be referenced in the HTML file.",
                      "default": true
                    }
                  },
                  "additionalProperties": false,
                  "required": [
                    "input"
                  ]
                },
                {
                  "type": "string",
                  "description": "The file to include."
                }
              ]
            },
```

Also interestingly enough the `lazy: true` option works and seems to be a workaround for me at the moment.

## 🔬 Minimal Reproduction

Just build any project that uses `inject: false` for any of the styles using the object syntax.

## 🔥 Exception or Error
<pre><code>
Data path ".styles[3]" should NOT have additional properties(inject).
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.3
Node: 13.3.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       8.2.3
@angular/cli                       9.0.3
@angular/material                  8.2.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.6
</code></pre>

**Comment by JoeFirebaugh** [comment]
It's possible this is a duplicate of #127 ... I'm not sure.  I'm reporting it in Angular 9.

**Comment by manfredsteyer** [comment]
Thanks for this info. Will be fixed with the next version that lands in some hours.
