### ISSUE TITLE
angular.json support object config for "optimization"

### ISSUE THREAD

**Issue by dartzki** [manfredsteyer/ngx-build-plus#187]
using angular-cli 9.1.3

the config option "optimization" in the angular.json file supports an object as value.
See https://angular.io/guide/workspace-config#optimization-and-source-map-configuration

using ngx-build-plus, the builder does not support the object format as value

**Comment by naveedahmed1** [comment]
Angular CLI 11.1.0-next.2 brings  some very useful optimizations including `inlining of critical CSS optimizations`, which can only be configured with support of object config for "optimization"

**Comment by manfredsteyer** [comment]
Thanks for this info. Will be resolved with the next version that lands in some hours.
