### ISSUE TITLE
Using the webpack externals.js gives error "Cannot read property 'ɵɵdefineComponent' of undefined"

### ISSUE THREAD

**Issue by alexbjorlig** [manfredsteyer/ngx-build-plus#188]
My objective with ngx-build-plus, is to serve a very small javascript file for my Angular application, consuming another angular web component.

Everything works when I serve the angular web component with:

```js
ng s --project <my-project-name> --single-bundle
```

But when I try to use the webpack externals command:

```js
ng s --extra-webpack-config projects/<my-project-name>/webpack.externals.js --output-hashing=none --project <my-project-name> --single-bundle
```

I get the following error when I try to use the web component:

```
<web-component-name>.component.ts:10 Uncaught TypeError: Cannot read property 'ɵɵdefineComponent' of undefined
```

Any help is very much appreciated 😅

**Comment by lukszymanski** [comment]
Are you using Angular 9?

**Comment by alexbjorlig** [comment]
Yes

**Comment by rapsspider** [comment]
Hi,

I'm try to understand what's happen, because i have the same problem.
It's seem that we define in webpack.external.js that @angular/core can be imported from the variable ng.core.

```javascript
/***/ "@angular/core":
/*!**************************!*\
  !*** external "ng.core" ***!
  \**************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = ng.core;

/***/ }),
```

What should define the variable ng.core ? The main application ? How ? :)

**Comment by rapsspider** [comment]
I think the main application must have externals in webpack.cofig too, and umd of all @angular must be present in angular.json.

The purpose is that the main angular application must use umd to allow the use of library for external angular component. So it's not an issue for me. Maybe the readme must explain an example for that.

Angular.json example :
```json
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./src/webpack.config.js"
            },
            ...
            "scripts": [
              {
                "bundleName": "polyfill-webcomp-es5",
                "input": "node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"
              },
              {
                "bundleName": "polyfill-webcomp",
                "input": "node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js"
              },
              "node_modules/rxjs/bundles/rxjs.umd.js",
              "node_modules/@angular/core/bundles/core.umd.js",
              "node_modules/@angular/common/bundles/common.umd.js",
              "node_modules/@angular/common/bundles/common-http.umd.js",
              "node_modules/@angular/compiler/bundles/compiler.umd.js",
              "node_modules/@angular/elements/bundles/elements.umd.js",
              "node_modules/@angular/forms/bundles/forms.umd.js",
              "node_modules/@angular/router/bundles/router.umd.js",
              "node_modules/@angular/animations/bundles/animations.umd.js",
              "node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
              "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"
            ]
          },
```

Maybe, we must run `ng g ngx-build-plus:externals` in the main application ? :)

**Comment by Maks-Yaremenko** [comment]
same issue.

**Comment by manfredsteyer** [comment]
Is Ivy activated?
Does running npx ngcc help?

**Comment by rapsspider** [comment]
I fixed it with somethink like "ng ngx-build-plus:externals" on the main application.

This error occured if umd file are not present. Be sûre that the main application use external ressources as umd :).

**Comment by manfredsteyer** [comment]
Very likely, you needed to add the UMD bundles to the angular.json's scripts section. Also, perhaps you needed to run ngcc again, so that the UMD buildes were converted to Ivy-UMD bundles.

**Comment by msmreen** [comment]
ngcc is not recognized as internal or external command
