### ISSUE TITLE
--extra-webpack-config is generating index.html twice

### ISSUE THREAD

**Issue by naveedahmed1** [manfredsteyer/ngx-build-plus#192]
I actually reported this issue on Angular CLI repo and they suggested to report it to `ngx-build-plus repo`

Can you please take a look at the issue https://github.com/angular/angular-cli/issues/17783

Thank you.

**Comment by manfredsteyer** [comment]
Thanks. The thing is, you should not use the ``HtmlWebpackPlugin`` b/c the CLI is always directly creating an ``index.html`` and we cannot change this from the outside.
