### ISSUE TITLE
Styles are not bundled with the .js file when using --single-bundle

### ISSUE THREAD

**Issue by mortenmoulder** [manfredsteyer/ngx-build-plus#197]
## Problem
I am creating multiple web components and have been for the past year or so. For my Angular 7 projects I've used `@angular-devkit/build-angular:browser` as builder and it works flawlessly. All my styles (SCSS) gets compiled and bundled within a single .js file. It works flawlessly.

However, I want to try out ngx-build-plus, but I can't seem to make my build process include the CSS within the actual bundled .js files. I am only interested in 1x .js file.

## Why does this matter?
My web components needs to be implemented into existing pages. Think newsletter signup. A newsletter signup web component is simple. It has an input text element and a button. Maybe recaptcha. The page does not know there is a web component and the web component does not know which page it's implemented on.

If I build my Angular 9 app like this:

```
ng build --prod --output-hashing=none --single-bundle --bundleStyles false --keepStyles false
```

I get these files:

- main-es5.js
- main-es2015.js
- polyfills-es5.js
- polyfills-es2015.js
- styles.css

Why is this a problem? Well, styles.css does not include any shadow DOM selectors specific to my web component. That means that the whole page I reference `styles.css` on, will get a lot of styles that can be used by other elements than my web component. This is bad behavior, because a web component's styles should only be shared with the web component.

## Fix?
Is there a fix? `@angular-devkit/build-angular:browser` does this beautifully and it works perfectly. One single .js file (after I bundle them together in the correct order) is all I need to reference on my page. I can live with es5 and es2015 for compatibility, but I do not want a separate styles file that every element on the page knows about.

Is that possible or should I go back to `@angular-devkit/build-angular:browser`?

**Comment by pirminrehm** [comment]
I use `ngx-build-plus` for bundeling all my styles and code into one file, using:
`ng build --single-bundle true --bundle-styles true --keep-styles true --prod --output-hashing=none`

This works fine for Angular 9. Nevertheless, be aware where you put in your global styles. If your root (default `app.component.ts`) uses the Shadow DOM via ` encapsulation: ViewEncapsulation.ShadowDom`, only the styles of the app component and benath components are packed inside the Shadow DOM. If you have styles in the global `styles.scss` (which is included via `angular.json`), they get not included. If you want to include other libraries like bootstrap, just add the imports to your root, e.g. `app.component.scss`.

**Comment by mortenmoulder** [comment]
@pirminrehm Ah, that makes a lot of sense.  Seems like my incompetence got the better of me. By building with your method, I can successfully bundle the styles within the compiled JavaScript file. It serves the same purpose as including a styles file, but at least it's bundled now.

Then I just need to use `ViewEncapsulation.ShadowDom` and call it a day. Perfect.

Thanks, I'll close this.

**Comment by petef19** [comment]
Hi,

could any of you elaborate on the `ViewEncapsulation.ShadowDom` setting ? is this needed or why do you use this setting in regards to styles in the bundle ?

As I outlined in #203, I use the build command from @pirminrehm above, and styles are bundled into one .js file (+ a sepaarte polyfill) but styles for the <body> or <html> tag are NOT applied (all other html tags work)... any idea why ?

Thanks !

**Comment by pirminrehm** [comment]
Hi @petef19,

the interesting question is: What are you using ngx-build-plus for?
I use it to single bundle Angular Micro Frontends as Web Component. In our Application we lazy load full Angular Apps, packed into one bundle via ngx-build-plus and exposed as Web Component. This is the reason, why we put it into Shadow DOM, to have an encapsulation to the other Micro Frontends. Shadow DOM prevents CSS to be applied to the outside and vice versa. For detail information take a look [here](https://developers.google.com/web/fundamentals/web-components/shadowdom).
Our Shell App, which loads these Micro Frontends, serves the general styling for `<body>` or `<html>` and defines where the Micro Frontend should be placed. It also includes all Polyfills once for all Micro Frontends. Thus, our single bundle Angular App (aka Micro Frontend) has only it's component styles. If you need to integrate general SCSS like utility classes, import them to the root component where the `ViewEncapsulation.ShadowDom` is applied. In doing so, they are available to all child components. Applying styles to the outside of the Shadow DOM is not possible.

So if you just want to single bundle a standard Angular project with ngx-build-plus, I have two ideas in mind:
1.  Use Shadow DOM on your root component, import there general SCSS you need, such as utility classes.
Be aware, that they only work for your root and child components. Put the few CSS for  `<body>` or `<html>` directly in the index.html for the general styling.
2. (not tested) Use `ViewEncapsulation.None` on your root component and all styles defined/imported here do not have the native or emulated encapsulation and thus are available everywhere.

I hope this helps you :)

**Comment by petef19** [comment]
@pirminrehm:

thanks for the detailed answer. Building a desktop app, and wanted the single .js file but including polyfill. We simply resided to concatenating whatever Ng is building into one .js file.

**Comment by manfredsteyer** [comment]
Unfortunately, this is currently not supported.
