### ISSUE TITLE
exports buildWebpackBrowserPlus

### ISSUE THREAD

**Issue by glebmachine** [manfredsteyer/ngx-build-plus#199]
I'm very glad you to share this awesome builder with us!

Could you export `executeBrowserBuilderPlus` method (like [angular team do](https://github.com/angular/angular-cli/blob/1d2e7bba07e1477fe3a551314ab93ad7aaa63420/packages/angular_devkit/build_angular/src/index.ts#L37)).
It allow builder developers to extend your awesome builder

**Comment by glebmachine** [comment]
Please, take a look @manfredsteyer, i've already made pr for this export

**Comment by manfredsteyer** [comment]
Good idea! It's now exported. Its name is ``buildWebpackBrowserPlus`` and you should find it in ``ngx-build-plus/browser``
