### ISSUE TITLE
Update to Angular 10

### ISSUE THREAD

**Issue by alyahmedaly** [manfredsteyer/ngx-build-plus#202]

**Comment by hisham** [comment]
Has anyone actually tested ngx-build-plus with angular 10? Does it work? Are there any issues?

**Comment by pirminrehm** [comment]
For me it worked without any problems on a small ng App.

**Comment by manfredsteyer** [comment]
Works. + I've just updated the version number to 10 to indicate this.

**Comment by manuel-cid** [comment]
Hi, can you provide an example of loading an external component using angular 10? I'm trying to reproduce your example from 
[angular-elements-dashboard (ng7)](https://github.com/manfredsteyer/angular-elements-dashboard/tree/ng7) with angular 10 and the component does not get rendered.
