### ISSUE TITLE
How compile the single bundle in fesm2015? 

### ISSUE THREAD

**Issue by ceoaliongroo** [manfredsteyer/ngx-build-plus#204]
I like to get the bundle ivy compile using angular cli, some of my code looks for the names of the Classes to performance specific code..

**Comment by manfredsteyer** [comment]
I'm afraid this is currently not possible, because webpack does not support fesm2015. However, you could create an ordinary library (ng g lib myLib) and build it. In this case, the CLI creates fesm2015 bundles
