### ISSUE TITLE
Request to update extraEntryPoint definition in schema.json

### ISSUE THREAD

**Issue by smsaad-qualtrics** [manfredsteyer/ngx-build-plus#211]
Hi there, 

I noticed our build was failing when upgrading our app from Angular 8 to Angular 9 and it was because of this error: 

```
An unhandled exception occurred: Schema validation failed with the following errors:
  Data path ".scripts[1]" should NOT have additional properties(inject).
  Data path ".scripts[1]" should be string.
  Data path ".scripts[1]" should match exactly one schema in oneOf.
```
It was because the property `inject` wasn't included in the schema for ngx-build-plus:browser build setting. What I had to resort to was used `"lazy": true` instead of `"inject": false` .
https://github.com/manfredsteyer/ngx-build-plus/blob/b2871c390ec61bf3afcf76d5fc499e1ebd109a99/lib/src/browser/schema.json#L373

So this is a request to update schema.json to reflect the new angular.json schema, or maybe point me in the right direction as to why the @angular-devkit/build-angular is not pulling in the right Angular 9 schema here (https://github.com/angular/angular-cli/blob/v9.1.11/packages/angular_devkit/build_angular/src/browser/schema.json). 

Thank you!

**Comment by manfredsteyer** [comment]
You could use a ngx-build-plus plugin for this.
