### ISSUE TITLE
Missing Type definition files

### ISSUE THREAD

**Issue by cstenglein** [manfredsteyer/ngx-build-plus#212]
Thanks for making this package Manfred! :+1: 

In the package on npm, there are only .js files for the builders.

Would you mind to add the .d.ts files in the build as well so we can import them properly in typescript?

Thank you! :)

EDIT: See my PR for the solution

**Comment by manfredsteyer** [comment]
Thx for pointing this out. d.ts-files will be there in version 11 that lands in some hours.
