### ISSUE TITLE
Can I integreate tailwind css into my angular project, when using ngx-build-plus?

### ISSUE THREAD

**Issue by alexbjorlig** [manfredsteyer/ngx-build-plus#219]
I am trying to adopt Tailwind CSS into my project, following [this guide](https://dev.to/seankerwin/angular-8-tailwind-css-guide-3m45).

In this guide, they ask to update the builder property in `angular.json` --> but I can't do that because I'm using ngx-build-plus 😎

So the question is, can I have 2 builders, or somehow extend ngx-build-plus with the webpack settings needed for Tailwind CSS?

**Comment by kylecordes** [comment]
This same question exists between every pair (n^2, ugh) of alternate builders for use with Angular CLI. Unfortunately for the moment, replacing the default builder with another one is the mechanism provided by the CLI. As more alternate builders become popular, there should be plenty of motivation to create an architecture suited for it, perhaps an array of plugins/builders rather than just one.

**Comment by alexbjorlig** [comment]
Good point. I found out about the `--extra-webpack-config` flag, and I'm now trying to combine the 2 objectives by doing: `ng s --project <name-of-web-cmpt-project> --single-bundle --extra-webpack-config webpack.config.js`. However, I'm struggling with that. Hope to get some help [here](https://stackoverflow.com/q/63265225/3694288), but if you have any idea about the issue help would be appreciated 1000 times 😊

**Comment by alexbjorlig** [comment]
I got the mentioned issue fixed, but now I'm having trouble because `ngx-build-plus` seems to ignore my styles in `src/styles.scss` when I use the `--single-bundle` flag. 

There seems to be many issues open with this, and I feel I have tried all combinations of `bundle-styles` and `keep-styles`, but the styles.scss are still not applied in the "single" bundle.

**Comment by manfredsteyer** [comment]
Yes, @kylecordes is right. Currently, we can only have one builder per target.

I've just created a new project with SCSS and bundled it using --single-bundle. It emits a styles.css with the styles from styles.scss.
