### ISSUE TITLE
`Styles.scss` not included, no matter the value of bundleStyles and keepStyles

### ISSUE THREAD

**Issue by alexbjorlig** [manfredsteyer/ngx-build-plus#220]
My objective is to build a single-bundle angular web component, with the styles from `styles.scss` included.

It seems to be impossible 🧐  No matter the combination of `--bundleStyles` and `--keepStyles`, the styles from styles.scss are not included in the `main.js` bundle.

I hope I'm missing something obvious here? My root component is using default encapsulation strategy (emulated).

**Comment by vekunz** [comment]
This is a bug in ngx-build-plus

**Comment by alexbjorlig** [comment]
> This is a bug in ngx-build-plus

Ok, do you know if there is a workaround somehow?

**Comment by vekunz** [comment]
Unfortunately, there is currently no workaround.

**Comment by alexbjorlig** [comment]
> Unfortunately, there is currently no workaround.

Do you know if there is a previous version that works, or maybe a fork?

**Comment by vekunz** [comment]
I don't know if there is an old version or a fork that fixes it. But there are two more issues about this problem.
https://github.com/manfredsteyer/ngx-build-plus/issues/145
https://github.com/manfredsteyer/ngx-build-plus/issues/91

**Comment by vokeit-gschuster** [comment]
This is caused by the change in utils/index.js.

Previously:
```
if (options.singleBundle && (options.bundleStyles !== false || options.keepStyles) && config.entry && config.entry['styles']) {
```

Current:
```
const keepStyles = options.bundleStyles || options.keepStyles;
if (options.singleBundle && !keepStyles && config.entry && config.entry['styles']) {
```

The logic is exactly contrary, previously itt said "when either bundleStyles OR keepStyles is true", now it says "both have to be false".

@manfredsteyer could you please verify if that is the desired behavior?
It "broke" our build that worked fine with 9.X

**Comment by CRACKISH** [comment]
Same error

**Comment by manfredsteyer** [comment]
@vokeit-gschuster Thanks for this great analysis. You are right. The comparisson was wrong.

Nethertheless, keepStyles only tells, if the global styles shall be built. If you now set it to false, they won't be built at all. Combining the styles.css and main.js bundles to one bundle is currently not possible, b/c ngx-build-plus delegates to the CLI's default builder.

However, you might achieve sth like this by configuring some webpack loaders or builders with an ngx-build-plus plugin.
