### ISSUE TITLE
How can we help, so ngx-build-plus will remain a maintained package?

### ISSUE THREAD

**Issue by alexbjorlig** [manfredsteyer/ngx-build-plus#221]
Hi everyone, and especially @manfredsteyer ☺️

Thanks for a great package, that includes some awesome tools. I hope you will take this message in a nice way.

With 69 open issues and 33 open pull requests, it seems like this package needs a helping hand 🤓

How can we help, so ngx-build-plus can be up to date and with minimal 🐛 🐞 ?

I think ngx-build-plus a very important role for enabling angular developers to provide single bundles, and other cool features.

**Comment by vandres** [comment]
May I ask, if ngx-build-plus will stay maintained since Angular offers now a "native" way to extend Webpack? 
https://www.npmjs.com/package/@angular-builders/custom-webpack

**Comment by manfredsteyer** [comment]
Hi Alex,

thanks for reaching out. I could really use some help with moderating issues (some of them are support requests) and with testing and merging PRs.

What do you think? Are you in?

Best wishes,
Manfred
