### ISSUE TITLE
Question: is it possible to work with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by maxisam** [manfredsteyer/ngx-build-plus#23]
Thank you for creating this great library.

AngularCli injects scripts and styles into index.html. However, I would like to use this library to generate separated script.html and style.html by using HtmlWebpackPlugin, so the scripts and style tags will go to those two files respectively. 

However, I can't make it work. All I got are 2 new empty files. It seems like htmlWebpackPlugin.files is empty. 

I wonder if it is possible to use this library to achieve what I am trying to do. Thanks !

**Comment by manfredsteyer** [comment]
I'm not sure. But perhaps the new feature in Version 7 that let's you point to an external custom config function.
