### ISSUE TITLE
Add option to merge polyfills.js to single bundle main.js

### ISSUE THREAD

**Issue by ngdevelop-tech** [manfredsteyer/ngx-build-plus#233]
When we use `--single-bundle` flag it merge `main.js`, `runtime.js` and `vendor.js` to `main.js`, and also generate `polyfills.js` and `styles.css`. This is expected behavior. `polyfills.js` is not required when we want to use this web component in other angular application. but when we want to use this generated web component in application other than angular like vanilla javascript, we will required the `polyfills.js`. 

So we can have one flag like `--mergePolyfill` which will also combine the `polyfills` with `main.js`. So that it is easy to use in non angular application. 

Please give your thought on this.

**Comment by manfredsteyer** [comment]
Thanks for this info. This is currently not planned for ngx-build-plus. But you can simplyy copy both files into one .js file if you really need it.
