### ISSUE TITLE
Please export serveWebpackBrowserPlus as well as you do wuth build function

### ISSUE THREAD

**Issue by glebmachine** [manfredsteyer/ngx-build-plus#236]
https://github.com/manfredsteyer/ngx-build-plus/blob/e04493c8f0611665d18ee4cdcefbb1415d62926d/lib/src/plus-dev-server/index.ts#L8

Could you please export this, to allow extend your awesome builder!
Thanks!

**Comment by manfredsteyer** [comment]
With pleasure. Will be exported in version 11 that lands in some hours.
