### ISSUE TITLE
[karma] Tests executed but not stopping itself

### ISSUE THREAD

**Issue by MDzyga** [manfredsteyer/ngx-build-plus#237]
Hi,
After upgrading your package to the latest version 11.0.0, unit tests are not stopped itself after tests execution completion.
It works fine when I use version 10.1.1.
Karma is configured as single run.

**Comment by cl-kazumi-nakajima** [comment]
@MDzyga Since that test is running in watch mode, I was able to solve the problem by making it false.

Add `watch: false` to the test configuration in angular.json.

**Comment by MDzyga** [comment]
thanks, it's working
