### ISSUE TITLE
dependency @angular-devkit/core@0.10.0 does not exist

### ISSUE THREAD

**Issue by markusdresch** [manfredsteyer/ngx-build-plus#24]
Just a small warning when installing ngx-build-plus:
`ngx-build-plus@7.0.2 requires a peer of @angular-devkit/core@~0.10.0 but none is installed. You must install peer dependencies yourself.`

that's a peerDependency in your package.json, but that version of angular-devkit/core does not exist. see https://www.npmjs.com/package/@angular-devkit/core

**Comment by bfaulk96** [comment]
https://github.com/manfredsteyer/ngx-build-plus/pull/25

**Comment by manfredsteyer** [comment]
Thanks for this info. Will look into it.

**Comment by manfredsteyer** [comment]
Thx for the PR! It's now in the current version.
