### ISSUE TITLE
Support for IE and Styles

### ISSUE THREAD

**Issue by sri1980** [manfredsteyer/ngx-build-plus#26]
Can you please let me know does this build cause any issues for IE support for angular elements?

Regarding styles, when we run the build we could see scripts.js and main.js. Can you please let me know how do we generate styles, is that bundled as part of one these .js files?

**Comment by manfredsteyer** [comment]
It also works with IE. You can put your styles into a css file at component level.

**Comment by sri1980** [comment]
Thank you for your response
