### ISSUE TITLE
Add option to  extraWebpackConfig somewhere centralized

### ISSUE THREAD

**Issue by euangoddard** [manfredsteyer/ngx-build-plus#3]
I've just integrated this fantastic library into my project to customize the webpack config, but I've found that I have to duplicate `--extraWebpackConfig webpack.extra.config.js` in many of my npm scripts. Moreover, I will need to ensure that any one who invokes `ng` directly does this to get the desired behaviour.

Could this value be put somewhere central, e.g. `package.json` or `angular.json` so that if the setting is there this option is used implicitly?

**Comment by manfredsteyer** [comment]
Thanks for this feedback. Currently, I don't have such a plan. IMHO it's also possible that one wants different webpack.config files for different tasks (e. g. build and serve).

**Comment by euangoddard** [comment]
Fair enough. I think both use-cases make sense, but I understand your position. Many thanks for getting back!

**Comment by MaxSagan** [comment]
I think this should be re-opened. The point of Angular.json is to configure the project, which includes configuring webpack. The point of ngx-build-plus is to allow us to configure webpack more granularly. Such granular configuration is generally pretty fundamental, so it would be advantageous to define it as part of the core configuration rather than as an option (i.e. a flag than can easily be accidentally left out).

**Comment by jcoutch** [comment]
Couldn't you just add the `extraWebpackConfig` option to your options array in angular.json for your various builds?

```
"architect": {
  "build": {
    "builder": "ngx-build-plus:build",
    "options": {
      "outputPath": "dist",
      ...
      "extraWebpackConfig": "webpack.extra.js"
    }
  }
}
```

I have it defined for both "build" and "serve", and works just fine.

**Comment by benwinding** [comment]
Thanks @jcoutch,
I didn't realise it needed to be in both **build** and **serve**.
Cheers,
Ben

**Comment by kylecordes** [comment]
BTW, the other tool for customizing webpack configs under Angular CLI:

https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack

takes the approach described above: an entry in angular.json to point to the extra webpack config.

(There are many other differences of course, but this one seems like it should be adopted from there over to here.)
