### ISSUE TITLE
Question: Reload Angular customElement during runtime

### ISSUE THREAD

**Issue by Lock-up** [manfredsteyer/ngx-build-plus#30]
Hi,
first of all thank you for this awesome package!

I dynamicly add the generated `main.js` file and create the custom element  during runtime.

Is it possible after making changes in my component to rebuild it, reload the main.js file from the server  and recreate the custom element with the changes (without page reload)?

Do you have any idea?

Kind regards
Jan

**Comment by manfredsteyer** [comment]
I'm pretty sure you need one reload.
