### ISSUE TITLE
Webcomponent does not render after update to Angular 7

### ISSUE THREAD

**Issue by dwadezp** [manfredsteyer/ngx-build-plus#31]
Hello,

i had successfully introduced webcomponents into our old legacy angular 1 application. 
I have one bundle because it's our non functional requirements and everything worked well.

But after updating to Angular 7 webcomponent does not render. I found that it's because runtime.js has to be in bundle as well. When i insert it manually in the bundle - webcomponent renders. But would like such things to be done under the hood. 

Also i notices that ngx-build-plus/sample also does not work now. Webcomponent is not rendered.

i'm building it in this way
`"build:watch": "ng build --vendor-chunk=false --delete-output-path=false --watch  --extraWebpackConfig webpack/webpack.dev-extra.js",`

webpack.dev-extra.js: 

```
module.exports = {
    "entry": {
        "item-html5": "src/main.ts"
    },
    "externals": {
        "lodash" : {
            commonjs: 'lodash',
            amd: 'lodash',
            root: '_' // indicates global variable
          },
          "jquery": 'jQuery'
    },
    "devtool": 'inline-source-map',

}
```

It will be good if you fix sample application and this should also solve my problem. Or maybe you have any ideas?

thanks in advance,
Vlad

**Comment by manfredsteyer** [comment]
Thanks for this. The sample is updated now and it should work.

The reason here is that --single-bundle now defaults to false to align with the CLI's default behavior. Hence, you need to set it explicitly to get one self-contained bundle when calling ng build:

```
ng build ... --single-bundle true
```
