### ISSUE TITLE
Sample application is broken

### ISSUE THREAD

**Issue by dwadezp** [manfredsteyer/ngx-build-plus#33]
Hello,

actually now sample project is broken. 
Steps: 
git clone https://github.com/manfredsteyer/ngx-build-plus.git
cd sample
npm install
npm run build
npm start

Actual result: blank page
Expected result: web component to be rendered

**Comment by manfredsteyer** [comment]
Thx for this info. I've fixed it. There were two reasons:

- --single-bundle defaults now to false to align with the CLI's default behavior, hence I had to add --single-bundle true to the build script
- the sample is now using ng 7 but loaded ng 6 bundles
