### ISSUE TITLE
--single-bundle true produces several files

### ISSUE THREAD

**Issue by gpiliponyte** [manfredsteyer/ngx-build-plus#346]
I would like to have a single js bundle for my Angular Element, however, I get 3 files produced:
![image](https://user-images.githubusercontent.com/29454703/188871719-2a17953a-7bdd-4bfd-9567-58aeba7d3d7b.png)

The build command used is the following: `ng build --configuration element --single-bundle true --output-hashing none`

Am I doing something wrong or is this an issue of the library? Any leads would be of great help.

**Comment by kumibrr** [comment]
I think it's normal behavior. To create single-file components, I use jscat (installed as dev-dependency) and execute the following command: `jscat ./dist/apps/${webcomponent}/*.js > ./dist/apps/${webcomponent}.js`

That way, I get a single file. I also use a script to build my project and automatically do the previous command in a single step.

**Comment by manfredsteyer** [comment]
Yes, this is how it is intended. Typically, you don't share your polyfills. the consumer has their own polyfills.
