### ISSUE TITLE
Possible to use Angular Material styles?

### ISSUE THREAD

**Issue by akrueger** [manfredsteyer/ngx-build-plus#35]
What is the best way to use Angular Material with this builder? I have tried importing material and cdk umd bundles after building, but all styles are bare.

Thanks

**Comment by akrueger** [comment]
It seems to work if I can generate a stylesheet, but there is no stylesheet output from `--single-bundle`.

**Comment by akrueger** [comment]
I found the `bundleStyles` option and that worked!

**Comment by Kartik1607** [comment]
Could you please post your solution. I am having same issue.

**Comment by PKief** [comment]
@Kartik1607 You can take a look at https://github.com/manfredsteyer/ngx-build-plus/issues/63#issuecomment-591263447, that finally worked for me regarding Angular Material.
