### ISSUE TITLE
Single-bundle do not work 

### ISSUE THREAD

**Issue by Leeron2010** [manfredsteyer/ngx-build-plus#36]
Hello. 
Probably I have missed something but something works wrong for me =(
I need to build one bundle for angular elements (runtime + polifils + style + vendor + main ). But build with --single-bundle true does not work.
I have created new project by Angular cli and add ngx-build-plus to it.

Enviroment - 
Angular CLI: 7.0.6
Node: 8.11.3
OS: darwin x64
Angular: 7.0.4

Build output - 
> single-output@0.0.0 build:minus /Volumes/Storage/Misha/Documents/Projects/single-output
> ng build --extraWebpackConfig webpack.extra.js --single-bundle false --delete-output-path --base-href=/single-output/dist/single-output/

                                                                                          
Date: 2018-11-20T23:06:48.227Z
Hash: 239e6179bab0b984a1d9
Time: 10116ms
chunk {main} main.js, main.js.map (main) 12.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.23 MB [initial] [rendered]
MacBook-Pro-Misha:single-output Misha$ npm run build:plus

> single-output@0.0.0 build:plus /Volumes/Storage/Misha/Documents/Projects/single-output
> ng build --extraWebpackConfig webpack.extra.js --single-bundle true --delete-output-path --base-href=/single-output/dist/single-output/

                                                                                         
Date: 2018-11-20T23:07:42.177Z
Hash: 4116a3520125962f1fdc
Time: 10449ms
chunk {main} main.js, main.js.map (main) 3.25 MB [entry] [rendered]
MacBook-Pro-Misha:single-output Misha$ 

As you could see I have build empty project twice, with --single-bundle true and false. 
With "--single-bundle false" I have standard 4 files as from default build - application start without any errors
With  "--single-bundle true" I have 1 file but application do not start with error in chrome console - 

>compiler.js:2547 Uncaught Error: Can't resolve all parameters for ApplicationModule: (?).
>    at syntaxError (compiler.js:2547)
>   at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:17874)
>    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:17767)
>    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:17635)
>    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:17445)
>    at compiler.js:17559
>    at Array.forEach (<anonymous>)
>    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:17547)
>    at CompileMetadataResolver../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:17445)
>    at compiler.js:17532

Thanks for your time =)

**Comment by DiogoDoreto** [comment]
It may be related to #4. Have you tried including zone.js in your page?

**Comment by StormRaider2495** [comment]
I am also facing this issue with **ngx-build-plus** single-bundle and I have also provided zone.js

Need a solution for fixing this.

**Comment by snerte** [comment]
This is because the polyfills will not be included in the bundle by design. The parameter `--keep-polyfills` will include the polyfills file.

**BUT** this will still be a seperate file. There is no option to generate one bundle including all files.
