### ISSUE TITLE
Angular 7.1 not supported

### ISSUE THREAD

**Issue by bterriervm** [manfredsteyer/ngx-build-plus#38]
Because of the versions in:

    "@angular-devkit/architect": ">= 0.10.0 < 0.11.0",
    "@angular-devkit/build-angular": ">= 0.10.0 < 0.11.0",
    "@angular-devkit/core": ">= 0.10.0 < 7.1.0",

It is not possible to upgrade to Angular 7.1 without error or warnings:

```
ng update --all
Package "ngx-build-plus" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires ">= 0.10.0 < 0.11.0", would install "0.11.0").
Incompatible peer dependencies found. See above.
```

It is possible to update by using `ng update @angular/core`. It seems to work without any issue, it just produces warnings during the update process

```
npm WARN ngx-build-plus@7.2.3 requires a peer of @angular-devkit/architect@>= 0.10.0 < 0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-build-plus@7.2.3 requires a peer of @angular-devkit/core@>= 0.10.0 < 7.1.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by manfredsteyer** [comment]
Thx for pointing this out! It's fixed now.
