### ISSUE TITLE
i got error messages when i used custom-element in angular 5 version

### ISSUE THREAD

**Issue by ArielBar** [manfredsteyer/ngx-build-plus#39]
Hey,
first of all thank you - you saved me with this solution. :)
but i have a little issue:
i created custom element called 'login-element' and tried to host it in angular 5 app,
eveythings look fine but

**when i loaded the js files in angular 5 app index.html file this way :**
  <script type="text/javascript" src="./assets/js/native-shim.js"></script>
  <script src="./assets/js/custom-elements.min.js"></script>
  <script type="text/javascript" src="./assets/js/rxjs.umd.js"></script>
  <script type="text/javascript" src="./assets/js/core.umd.js"></script>
  <script type="text/javascript" src="./assets/js/common.umd.js"></script>
  <script type="text/javascript" src="./assets/js/platform-browser.umd.js"></script>
  <script type="text/javascript" src="./assets/js/elements.umd.js"></script>
  <script type="text/javascript" src="./assets/js/login-element.js"></script>
**i got this error:**
ERROR DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry

**and when i tried to load them this way:**
  <script type="text/javascript" src="./assets/js/login-element.js"></script>
  <script type="text/javascript" src="./assets/js/native-shim.js"></script>
  <script src="./assets/js/custom-elements.min.js"></script>
  <script type="text/javascript" src="./assets/js/rxjs.umd.js"></script>
  <script type="text/javascript" src="./assets/js/core.umd.js"></script>
  <script type="text/javascript" src="./assets/js/common.umd.js"></script>
  <script type="text/javascript" src="./assets/js/platform-browser.umd.js"></script>
  <script type="text/javascript" src="./assets/js/elements.umd.js"></script>

**i got this error:**
Uncaught ReferenceError: ng is not defined
    at Object.<anonymous> (login-element.js:1)
    at r (login-element.js:1)
    at Module.<anonymous> (login-element.js:1)
    at r (login-element.js:1)
    at Object.<anonymous> (login-element.js:1)
    at r (login-element.js:1)
    at login-element.js:1
    at login-element.js:1

What am I not doing right?

**Comment by manfredsteyer** [comment]
Hi,

it's only supported beginning with version 6.

Best wishes,
Manfred

**Comment by ArielBar** [comment]
I know, I hosted a nap angular 7 element in angular 5 app and I got that messages.
