### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by Timebutt** [manfredsteyer/ngx-build-plus#398]
Angular `17.0.0` [just released](https://blog.angular.io/introducing-angular-v17-4d7033312e4b), but upgrading to that new version with `ngx-build-plus` as a dependency throws this error when running `ng serve`:

```
This version of CLI is only compatible with Angular versions ^16.1.0,
but Angular version 17.0.0 was found instead.
```

Dropping this issue as a go-to reference for others to keep track of the progress!

**Edit**:
For others experiencing this same issue and who can't wait to get started with `Angular 17.0.0` you can always override nested peer dependencies and still get everything running. If you are using `yarn`, you can add the following to your `package.json`, run `yarn install` and you should be good to go for now!

```
"resolutions": {
    "@angular-devkit/build-angular": "^17.0.0"
}
```

I'm currently testing above approach and my medium-sized Angular application seems to be running just fine!

**Comment by scottwalter-nice** [comment]
Using "overrides" for NPM also works.

**Comment by kristijanprematarov** [comment]
> Using "overrides" for NPM also works.

Could you give an example

**Comment by muenchto** [comment]
@scottwalter-nice how exactly did make it work for NPM? Can you post your code? I am kinda stuck..

**Comment by Timebutt** [comment]
Version `17.0.0` of this package released quite some time ago, you shouldn't need any workaround anymore.
