### ISSUE TITLE
Production build with --single-bundle results in "In this configuration Angular requires Zone.js" error

### ISSUE THREAD

**Issue by SirDieter** [manfredsteyer/ngx-build-plus#4]
I tried to create a production build with additional webpack.extra.js:
`module.imports = {
   output: {
      jsonpFunction: "BLABLABLA"
   }
}`
Running `ng build --prod --extraWebpackConfig webpack.extra.js`  results in 

> Uncaught Error: In this configuration Angular requires Zone.js

Running `ng build --prod --extraWebpackConfig webpack.extra.js --single-bundle false` works fine

**Comment by manfredsteyer** [comment]
That means, you load the custom element into a NON-Angular-application, right?

Angular uses zone.js by default for change tracking, so you have to make sure that it is loaded into the browser too. When the target app is an angular application, zone.js is there.

If not, you can referene it directly:
 <script src="./zone.js"></script> 

The script is somewhere under node_modules in your Angular-Project. You can copy it from there.

You could also try to exclude Zone.js from your Elements-Project (search for noop-zone one the web). But here, the consequence is that you need to do change tracking by your own.

**Comment by tnicola** [comment]
@manfredsteyer I got the same error. I'm importing zone.js in my polyfills but the polyfills file isn't packed into the final bundle. I understand that doing this means potentially having lots of zone.js in the same browser and raise other error but I think it could be fine to let the decision to the library user. So, my question is: Does it make sense to add an option `--include-polyfills` to the library? Thanks.

**Comment by LoganDark** [comment]
Just import `zone.js` in `main.ts`:

![image](https://user-images.githubusercontent.com/4723091/44953732-66307780-ae4c-11e8-8a65-df7bbe30f5aa.png)

Fixed it for me.

**Comment by dongdongmao** [comment]
Just import zone.js in main.ts seems work but throw a error

Uncaught Error: Zone already loaded.
    at zone.js:32
    at zone.js:21
    at zone.js:9
    at Object.<anonymous> (zone.js:8)
    at Object.164 (zone.js:3048)
    at j (bootstrap:782)
    at r (bootstrap:150)
    at Module.<anonymous> (polyfills.ts:1)
    at j (bootstrap:782)
    at r (bootstrap:150)

**Comment by LoganDark** [comment]
@dongdongmao You should, you know, remove it from the other file too.

**Comment by dongdongmao** [comment]
yes it worked thanks

**Comment by LoganDark** [comment]
@dongdongmao YW

**Comment by NelsonLamprecht** [comment]
The import of the zone.js in main worked but can anyone explain why I have to do this? I don't have to do this in other angular apps?

**Comment by maktarsis** [comment]
@NelsonLamprecht you are free to import zonejs in polyfills file.

But if you are asking about zonejs as angular app dep, so you are also free to don't use it. Read about how to disable zonejs at all.

**Comment by arodr967** [comment]
@SirDieter you could also use `defer` instead of `async` on the script tag in your `index.html`

```
<script defer type="module" src="angular-elements.js"></script>
```

this makes sure that your `angular-elements` is loaded after your angular application has loaded it's own `zone.js` --  it also increases [page load performance](https://angularfirebase.com/lessons/angular-elements-advanced-techniques/)

**Comment by Mobiletainment** [comment]
To wrap it up: if you want to include zone.js within your single bundle, then import it in `main.ts` using:
```typescript
import 'zone.js/dist/zone';
```

This is the correct deep-import (which is also used in `polyfills.ts`).

**Comment by hisham** [comment]
In Angular 10, I get this warning: 

```
WARNING in /Users/hisham/src/ess-app/frontend/projects/elements/src/main.ts depends on 'zone.js/dist/zone.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Any way to resolve this warning without just adding zone.js to allowedCommonJsDependencies?

**Comment by patilc1** [comment]
@manfredsteyer I am getting this error in angular application, I have imported custom element bundle from assets folder and placed custom element in app.component.html, i have already imported zone.js in angular application in main.ts file

**Comment by MichaelDevPL** [comment]
In file polyfills.ts change `/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
// import 'zone.js/dist/zone';  // Included with Angular CLI.
import 'zone.js';
`
And the error disappears

**Comment by MichaelDevPL** [comment]
In file polyfills.ts change import

 'zone.js/dist/zone'  on  'zone.js';

And the error disappears

**Comment by fuchunhui** [comment]
> To wrap it up: if you want to include zone.js within your single bundle, then import it in `main.ts` using:
> 
> ```ts
> import 'zone.js/dist/zone';
> ```
> 
> This is the correct deep-import (which is also used in `polyfills.ts`).

it's work.

**Comment by junaid5546** [comment]
What is the point of importing zone.js while angular 18 is zoneless
