### ISSUE TITLE
Bundle output include comments

### ISSUE THREAD

**Issue by DanielNetzer** [manfredsteyer/ngx-build-plus#40]
webpack.extra.js
```
const uglifyJSPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  "externals": {
    "rxjs": "rxjs",
    "@angular/core": "ng.core",
    "@angular/common": "ng.common",
    "@angular/platform-browser": "ng.platformBrowser",
    "@angular/elements": "ng.elements"
  },
  "output": {
    library: "omegaChatBot"
  },
  plugins: [
    new uglifyJSPlugin({
      uglifyOptions: {
        output: {
          comments: false
        }
      }
    })
  ]
}
```

Trying to add uglifyJSPlugin to the webpack extra result in a failure with the following error.

```
ERROR in scripts.js from UglifyJs
Unexpected token: keyword (const) [scripts.js:29,2]
```

**Comment by manfredsteyer** [comment]
That should not be necessary. Did you call ``ng build`` with ``--prod-``?
In which file do you see the comments?

**Comment by DanielNetzer** [comment]
main.js include the comments, and I did used ng build with --prod.
I copied the scripts from the sample application on this repo.
I eventually managed to add the uglifyJSPlugin to the build so the comments got removed.
all of the comments are @license comments of google
