### ISSUE TITLE
Angular Custom elements library

### ISSUE THREAD

**Issue by sri1980** [manfredsteyer/ngx-build-plus#41]
I would like to get one clarification before using this library. I had use case to display two angular elements in one browser window. I first tried with default angular devkit build and it was not supporting, getting error when i tried to add second angular element to DOM. 

With ngx-build-plus i am not seeing any issues, i am able to display multiple angular elements in window. i am not using webpackextraconfig.js. 

Trying to understand are you doing anything by default in this build to support this bevaviour (related angular elements library).

I looked at the code, couldn't understand much.

Thanks in advance.

**Comment by manfredsteyer** [comment]
it works with several bundles b/c it produces one single bundle per project. When webpack creates several bundles for one project it introduces a global variable. And when loading bundles from different projects, this global variable is overwritten and hence it stops working.

An alternative would be to rename this global variable in the bundles. However, I guess its best, for most web components to just come with one bundle.

**Comment by sri1980** [comment]
Thanks for your response. Can you please let me know what is that global variable introduces with default angular cli build and are we eliminating this variable in tngx-build-plus output bundle?
