### ISSUE TITLE
ng build MyLib responding Unknown option: '--project'

### ISSUE THREAD

**Issue by danielpcampagna** [manfredsteyer/ngx-build-plus#46]
## Versions

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.1.4
Node: 11.3.0
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.4
@angular-devkit/build-angular      0.11.4
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.11.4
@angular-devkit/build-webpack      0.11.4
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.1.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.4
@schematics/angular                7.1.4
@schematics/update                 0.11.4
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

```

## Description

After creating my lib (`ng generate library my-lib`) and setting `ngx-build-plus` manually [1], I did try to follow [this another example](https://github.com/manfredsteyer/ngx-build-plus#another-example-externals-and-angular-elements), however, I`ve got this error, on build.

```cmd
> ng build my-lib --extraWebpackConfig webpack.extra.js --output-hashing none --single-bundle true

Unknown option: '--project'
```

## Steps

- Create a project and a library

```cmd
> ng new myApp
> cd myApp/
> ng generate library my-lib
```

- follow [this another example](https://github.com/manfredsteyer/ngx-build-plus#another-example-externals-and-angular-elements) installing dependencies to the library.

```cmd
> ng add @angular/elements --project my-lib
> npm install @webcomponents/custom-elements --save
```

[On step 2](https://github.com/manfredsteyer/ngx-build-plus#another-example-externals-and-angular-elements), add this changes on `./projects/my-lib/src/lib/my-lib.component.ts`.

On step 3, install `ngx-build-plus` manually [1].

step 5, add `webpack.extra.js` on the root project.

And 6, finally, build the library to get this message error:

```cmd
> ng build my-lib --extraWebpackConfig webpack.extra.js --output-hashing none --single-bundle true

Unknown option: '--project'
```

## Notes

1. Why did I setting `ngx-build-plus` manually?

When I did install using Angular CLI, I got this error

```
> ng add ngx-build-plus --project my-lib

expected node projects/my-lib/architect/serve in angular.json
```

## Context

I need to create a `umd` file from my angular library (as the angular builder does).
However, I need to customize my build process, because I need to include some dependencies into this file (E.g. `@angular/material`) and another I'll send as parameter.

**Comment by manfredsteyer** [comment]
Thanks for this detailed description. Unfortunately, ngx-build-plus does not support libraries, as they are not build with webpack. For libs, the CLI uses an own builder that bases upon ng-packagr which in turn uses its own logic.
