### ISSUE TITLE
Should ngx-build-plus use merge() or merge.smart()?

### ISSUE THREAD

**Issue by joeldenning** [manfredsteyer/ngx-build-plus#50]
From what I can tell from the documentation, webpack-merge's [merge.smart()](https://github.com/survivejs/webpack-merge#mergesmartconfiguration-configuration) function is better at merging webpack configs than a plain `merge()` is. The merge.smart() function does a better job of merging the `loaders` and `module.rules` webpack configuration, and maybe some other parts of the config.

Thoughts on whether ngx-build-plus should switch over to merge.smart()?

**Comment by manfredsteyer** [comment]
Thanks for this idea. For more advanced scenarios, I would recommend using plugins as they give you a very fine-grained control over the config. You can find sth. about this at [1] -- see "using plugins" and "Using different merging strategies":

https://www.npmjs.com/package/ngx-build-plus
