### ISSUE TITLE
lazy load module is not generated If extraWebpackConfig is provided

### ISSUE THREAD

**Issue by TomKubik** [manfredsteyer/ngx-build-plus#51]
Not sure why, but if I use extraWebpackConfig to not have some libraries in the bundle (using externals), the lazy module definition e.g. { path: 'page2', loadChildren: "./page2/page2.module#Page2Module" } is completely ignored and it's not generated (= no chunk exist). The extraWebpackConfig file may be even empty. If I remove this option (from 

> _ng build --prod --project module-a --extraWebpackConfig webpack.extra.js --output-hashing none_

 to 

> _ng build --prod --project module-a --output-hashing none_

) then everything is ok, chunk generated. Any known troubles with lazy modules?

**Comment by manfredsteyer** [comment]
yes, this is currently a limitation. Using both, externals and lazy loading is not supported [1]. However, when already having externals, doing lazy loading by hand is not that difficult. 

[1] https://github.com/angular/angular-cli/issues/11490

**Comment by manfredsteyer** [comment]
Btw: Currently, I'm working on a schematic to make using externals easier:
```
ng g ngx-build-plus:externals 
```

generates the basic setup for you. More info abt this is in the pipeline.

**Comment by osmanmeer** [comment]
> yes, this is currently a limitation. Using both, externals and lazy loading is not supported [1]. However, when already having externals, doing lazy loading by hand is not that difficult.
> 
> [1] [angular/angular-cli#11490](https://github.com/angular/angular-cli/issues/11490)

Hey @manfredsteyer - thanks for the response. Could you please elaborate on what you meant by "lazy loading by hand"?
