### ISSUE TITLE
Add missing LICENSE

### ISSUE THREAD

**Issue by mbenzenhoefer** [manfredsteyer/ngx-build-plus#57]
Can you please add a LICENSE file and set the license type in your repo? Also for ngx-build-modern.

If you want me to, I will create a PR to add these files. Just let me know.

**Comment by manfredsteyer** [comment]
Yes, will do. Package.json already mentions MIT, but I will also add a LICENSE file.

**Comment by manfredsteyer** [comment]
Added.

**Comment by mbenzenhoefer** [comment]
Can you also publish this with your npm package and link it in the github repository through its settings? This helps automatizing the fulfilling of license obligations. Thanks a lot!
