### ISSUE TITLE
Breaks build when using jest

### ISSUE THREAD

**Issue by Twista** [manfredsteyer/ngx-build-plus#59]
Hello, I just tried to use the library, unfortunately, it's breaking build because of jasmine (we are using jest for testing)

version: ngx-build-modern@1.1.3

running regular (old) build (`ng build --prod --configuration=production`)
![1____w_a_c_dashboard__fish_](https://user-images.githubusercontent.com/1297511/50991548-2faeeb80-1515-11e9-8639-805806fea252.png)

running modern build (`yarn run build:modern`)
![1____w_a_c_dashboard__node_](https://user-images.githubusercontent.com/1297511/50991842-e90dc100-1515-11e9-9cff-c4fa40af5107.png)

When removed jasmine (diry `rm -rf jasmine @types/jasmine`) build was succesfull (with both cases).

only library (based on yarn list) which brings jasmine into the project is this one. Do you think it will be solvable? (e.g move jasmine to devDependencies).

Also, let me know if any other information is needed, will be glad to help :)

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. The lib has not been tested with jest and the test builder is delegating to the CLI's karma-builder. Feel free to add a PR for supporting jest.
