### ISSUE TITLE
Dynamically Adding Angular elements

### ISSUE THREAD

**Issue by PrayooshGL88** [manfredsteyer/ngx-build-plus#6]
Hello,

Apology for adding it as an issue, we have a requirement as given below:

We have a requirement for creating a dynamic dashboard, which can hold the widgets coming from various third-party servers.
We thought of having the dashboard developed in Angular and all the widgets will be developed as Angular elements. 
Another requirement we have is like the dashboard code will be hosted on some server and is not required to update or modify the source code for the widget.
We have been following you for the ng-zone already initialized error. 

Can you please help us in identifying a proper mechanism for implementing it?

Appreciate the help.

Thanks!

**Comment by manfredsteyer** [comment]
I think, this could help: https://www.softwarearchitekt.at/post/2018/07/13/angular-elements-part-i-a-dynamic-dashboard-in-four-steps-with-web-components.aspx
