### ISSUE TITLE
How to use with `ng test`?

### ISSUE THREAD

**Issue by simbo** [manfredsteyer/ngx-build-plus#60]
angular 7.1.4
cli 7.1.4
ngx-build-plus 7.6.0

I've set up the example from the readme using `webpack.DefinePlugin` and the `--plugin` option.
Works fine using `build` and `serve`, but i can't get the tests running as the custom webpack config seems to be ignored.

How to solve this?

[edit]
to be more precise:
i checked out ngx-build-plus and tried your `getting-started` project which seems to have the same problem: tests fail with `VERSION is not defined`...

Please tell me this is somehow solvable... :)

**Comment by manfredsteyer** [comment]
There is currently no Builder for ng-test. But you are right, in the case of DefinePlugin you'd need it. It is not difficult to create support for ng test. Please give me some days, I'll publish a new version with support.

**Comment by jcoutch** [comment]
I ran into this last week as well.  Test support would be awesome!

**Comment by manfredsteyer** [comment]
Test support just landed with the current version.

**Comment by simbo** [comment]
Yeah! Thank you very much! This came just in time. ;)
