### ISSUE TITLE
SCSS not build

### ISSUE THREAD

**Issue by tobang** [manfredsteyer/ngx-build-plus#63]
Hi. ngx-build-plus builds the project just fine and scripts.js and main.js files are built correctly. But I would also expect there to be a styles.css file, but it is not build. As I am using sass, do I need some kind of plugin to compile sass files?

Thank your for your effort building this library

Torben

**Comment by tobang** [comment]
Closing issue. I misunderstood the single-bundle option.

**Comment by MrCroft** [comment]
@tobang could you mention how did you solve the styles issue?
I've just ran into the same thing, but I have no clue as to how to get my styles in the final bundle or (ideally) a separate css file (I usually like to use --extract-css, but with ngx-build-plus I don't get the styles, either way).

**Comment by tobang** [comment]
@MrCroft I use the following commang to get the styles separated:
ng build <projectname>  --prod --extraWebpackConfig webpack.extra.js --output-hashing none --single-bundle true --bundle-styles false

**Comment by artem-galas** [comment]
Do you know how to build styles to separate css file instead of one `style.css`.
For example i have `style.scss` and `customer.scss` so I would like to have them both in final build.

**Comment by amilaI** [comment]
In my case this command worked with --keepStyles false.
**ng build --prod --output-hashing none --single-bundle true --bundleStyles false --keepStyles false**

**Comment by markusdresch** [comment]
@amilaI  thank you!! this worked, had me pulling my hair out.

**Comment by sonic1981** [comment]
It seems that styles are only bundled in if they are component styles or referenced in code. This seems to be deliberate https://github.com/manfredsteyer/ngx-build-plus/issues/197#issuecomment-641779683
