### ISSUE TITLE
Using multiple angular custom elements in angular CLI project

### ISSUE THREAD

**Issue by tryCatchPizza** [manfredsteyer/ngx-build-plus#65]
Is it possible to use "ngx-build-plus" for building multiple angular custom elements and consume them in angular CLI project? I'm asking since in "ngx-build-plus/sample" newly built element is used in index.html file, which includes files from angular/core,common, etc..., Also i've tried to create elements and use them in angular CLI project but unsuccessfully.

**Comment by manfredsteyer** [comment]
Yes, it's possible. You find an example here: https://www.softwarearchitekt.at/post/2018/07/29/angular-elements-part-ii-lazy-and-external-web-components.aspx

**Comment by vkvarma** [comment]
@manfredsteyer if we want to add two different angular v8 element(build from 2 micro-apps) into container angular v8 application provided each micoapp using ngrx store and app-container has also ngrx store.
