### ISSUE TITLE
devServer properties are not merged properly

### ISSUE THREAD

**Issue by christianscharr** [manfredsteyer/ngx-build-plus#66]
In our project we have to attach some additional CORS related headers to webpack-dev-server when starting locally with _ng serve_.
Following the [docs](https://webpack.js.org/configuration/dev-server/#devserver-headers-), it should be possible. But the necessary properties in our webpack.partial.js seems to simply ignored on startup.

```javascript
module.exports = {
  //...
  devServer: {
    headers: {
      "Access-Control-Allow-Origin": "https://localhost.intranet:8081",
      "Access-Control-Allow-Credentials": "true"
    }
  }
};
```

**Comment by manfredsteyer** [comment]
Are you sure?

To hunt this down, I've enabled a --verbose flag in the latest version of ngx-build-plus (just published it).

The following

```
ng serve --project getting-started --verbose --extra-webpack-config webpack.partial.js
```

would print out the modified config to the console. In my case, it includes this devServer section.

Can you pls have a look at it?

**Comment by christianscharr** [comment]
Yes, I am sure.
Using the new --verbose flag I see the properties are injected correctly but it seems they are overwritten later or something like that, because webpack-devserver doesnt take notice from them...

**Comment by christianscharr** [comment]
I took s look at your implementation and the original builder.
The problems seems to be located at [this line](https://github.com/angular/angular-cli/blob/1a3ba03a5974575ce34fe02d36b906d17691523a/packages/angular_devkit/build_angular/src/dev-server/index.ts#L150)

The original implemtation does an hard override of devServer properties with the return value of _buildServerConfig()

**Comment by markuseckstein** [comment]
@christianscharr Did you find a solution for that? I'm facing the same problem, the custom devServer configuration gets overwritten with the defaults just before it is passed to webpack-dev-server.

**Comment by christianscharr** [comment]
Hi @markuseckstein yes I found one but had not yet the time to create an PR to put it back here to @manfredsteyer ...
You can take a look at [my fork](https://github.com/christianscharr/ngx-build-plus/) it's solved there

**Comment by markuseckstein** [comment]
Thank you @christianscharr , this works like a charm!

**Comment by kylietmo** [comment]
Would also appreciate if this issue was re-opened because I have run into the same issue.
