### ISSUE TITLE
Builder for universal/server (ngx-build-plus:server)

### ISSUE THREAD

**Issue by kuhnroyal** [manfredsteyer/ngx-build-plus#67]
Do you think it is possible to add a custom builder for `@angular-devkit/build-angular:server` which also accepts an `extraWebpackConfig` path?

I now have some custom configuration for `build/dev-server` but can not get my universal/app-shell to work because the configuration is missing there and I can't find a way to hook it in.

**Comment by gcirone** [comment]
I think is necessary to add the support for server build or become hard to manage the difference between builds.

**Comment by dsg-cmcmurray** [comment]
I also found myself looking for this...would like this as a feature request.  For anyone doing @nguniversal, this would be extremely helpful

**Comment by tommck** [comment]
_\*hears crickets\*_

**Comment by manfredsteyer** [comment]
Thanks for this info. Currently, we don't have a server builder. Feel free to provide a PR for it.
