### ISSUE TITLE
provide more control over configuration and allow using ts for webpack config

### ISSUE THREAD

**Issue by shlomiassaf** [manfredsteyer/ngx-build-plus#7]
Hi,

In the past I've built a library that does the same thing as this one but without native integration, which means monkey patching and dedicated cli command...

This lib takes the native approach, which is, of course, **a significant** improvement and the best way to go.

I'v upgraded my library to do the same thing (code copy 💯 ) this lib does but with 2 features I was missing.
I would be happy to pass them into this repo, if you want:

- Use `.ts` config files (as long as `ts-node` exists)

- Provide a function instead of a configuration object (objects are still supported tough)

The first feature is straightforward... the 2nd:

`ngx-build-plus` excepts a webpack configuration object which it merges into the
original configuration produces by the cli.

A function accepts a single parameter, the original configuration object
generated by the angular cli. Internally, the function can modify the object or return a new
object that will be used as the configuration object sent to webpack.

#### Why?
Using a function provides a high level of control over the configuration file.

Under the hood, `ngx-build-plus` is using [webpack-merge](https://github.com/survivejs/webpack-merge) to do the merging. `webpack-merge` has
a lot of features and merging strategies which you can't use, with a function you
can do the merging manually.

`webpack-merge` aside, sometimes you want to apply complex logic on the config
that act's based on certain conditions, removing things, adding things etc.. this is
not possible with merging.

See more [here](https://github.com/shlomiassaf/ng-cli-ext)

Thanks!

**Comment by manfredsteyer** [comment]
Sth like this is now in Version 7 of this lib.
