### ISSUE TITLE
angular.json schema validation fails on es5BrowserSupport when using @angular/cli 7.3.0

### ISSUE THREAD

**Issue by Akkenar** [manfredsteyer/ngx-build-plus#70]
Hi,

When using `ng-build-plus` with `@angular/cli` 7.3.0, I'm getting the following message:

```
$ yarn build
yarn run v1.13.0
$ ng build
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(es5BrowserSupport).
```

`es5BrowserSupport` has been added recently to `@angular/cli` in `angular.json`. It dynamically loads some es5 polyfills depending on the browser rather than loading them in `polyfill.js`. 

```diff
 "architect": {
   "build": {
     "builder": "ngx-build-plus:build",
     "options": {
       "outputPath": "dist/ngx-build-plus-cli73",
       "index": "src/index.html",
       "main": "src/main.ts",
       "polyfills": "src/polyfills.ts",
       "tsConfig": "src/tsconfig.app.json",
       "assets": [
         "src/favicon.ico",
         "src/assets"
       ],
       "styles": [
         "src/styles.css"
       ],
       "scripts": [],
+      "es5BrowserSupport": true
```

It's annoying because a new Angular projects created with the latest version of the CLI will have the issue.

# Steps to reproduce

- Install the latest version of `@angular/cli` globally: `yarn global add @angular/cli`
- Create a new project: `ng new my-new-project`
- Add `ngx-build-plus`: `ng add ngx-build-plus`
- Build: `yarn build`

Repo with this workflow available there: https://github.com/Akkenar/ngx-build-plus-cli73

# Actual Result
The project doesn't pass the `angular.json` schema validation as per the message above.

# Expected Result
I guess to be able to use this `es5BrowserSupport` feature with `ngx-build-plus`.

I suspect this is "only" an issue with the `angular.json`. To be confirmed.

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. I'll work on it until Tue evening.

Meanwhile -- as a quick hot fix --  you can just update the schema.json in the ``node_modules`` folder.

Best wishes,
Manfred

**Comment by mselerin** [comment]
Another temporary quick fix is to remove the `es5BrowserSupport` option from angular.json (and add it back when ngx-build-plus is patched) ;-)

**Comment by toxik** [comment]
I also have a problem with the new `sourceMap` property which migrated from a boolean to an object and I cannot use it.

**Comment by manfredsteyer** [comment]
Thanks for providing a quick fix. It's fixed now.

**Comment by acidghost** [comment]
@manfredsteyer how is this fixed?

**Comment by Akkenar** [comment]
@manfredsteyer thanks for the fix, I'm now able to use `es5BrowserSupport` with ngx-build-plus.

**Comment by zack9433** [comment]
@manfredsteyer `sourceMap` still can not set as object like

```
sourceMap: {
  scripts: true,
  hidden: true
}
```

**Comment by zyrain** [comment]
Run "npm update --dev"  you updated the CLI without updating @angular-devkit/build-angular to 0.13.5

**Comment by fazliraziq** [comment]
I was facing this issue because my installed version @angular/cli does not match cli version mention in package.json. Downgrading to the angular cli version i have fixed this issue. in my case
`npm install @angular/cli@9.1.4`
