### ISSUE TITLE
How can we build n Elements with n seperate js-bundles from a single app?

### ISSUE THREAD

**Issue by andreElrico** [manfredsteyer/ngx-build-plus#81]
How can we build n separate Elements and compile them into n separate bundles out of a single app.

I need n separate bundles because I dont want every user to "see" every Angular Element.
Is there still a way to share dependencies or injectors?

**Comment by manfredsteyer** [comment]
I'm afraid, there is currently no easy solution for this. You could provide a partial webpack config which has one entry point for each web component.
