### ISSUE TITLE
Support of protractor builder

### ISSUE THREAD

**Issue by andrui** [manfredsteyer/ngx-build-plus#85]
I have used ngx-build-plus in order to inject HtmlWebpackPlugin to add templating syntax into index.html. With 'serve' and 'build' all is ok. But similar functionality is needed for running protractor tests. It would be nice to have 'ngx-build-plus:protractor'

**Comment by duanemck** [comment]
I'm experiencing the same issue. All works nicely for build an serve, but I need a particular webpack loader injected for `ng test`. The config override is not applied. If I try the plugin approach, `pre()` and `post()` are called but not `config()`

**Comment by stevengunneweg** [comment]
I'm also running into this issue.
Is there any update, workaround or maybe someone who made a relevant fork?

**Comment by manfredsteyer** [comment]
Please have a look here #222
