### ISSUE TITLE
Angular 8b13: Could not find the implementation for builder ngx-build-plus:dev-server

### ISSUE THREAD

**Issue by jmesa-sistel** [manfredsteyer/ngx-build-plus#93]
Since Angular 8b11 I have the error:
`Could not find the implementation for builder ngx-build-plus:dev-server
Error: Could not find the implementation for builder ngx-build-plus:dev-server
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (D:\web\bps_webapp\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:45:19)`

Seems that they have done changes in API
[support stable architect API](https://github.com/angular/angular-cli/pull/13994)

More info:
[architect API](https://docs.google.com/document/d/1SpN_2XEooI9_CPjqspAcNEBjVY874OWPZqOenjuF0qo/view)

**Comment by Timebutt** [comment]
We are setting up a branch with the latest Angular 8 `RC.0` to prepare our upgrade path and are currently experiencing the same issue. I don't know if a fix can be done to support both the newest version of Angular 8 and be backwards compatible?

**Comment by jmesa-sistel** [comment]
@Timebutt 
Seems that @manfredsteyer is working on it:
[cli8 branch](https://github.com/manfredsteyer/ngx-build-plus/tree/cli8)

**Comment by Timebutt** [comment]
Ah great news! Wanted to bump your thread as I didn't see a reply here yet ;)

**Comment by manfredsteyer** [comment]
Yes, there is already a cli8 branch and I'll release a RC for CLI 8 soon.

**Comment by jmesa-sistel** [comment]
I'll close the issue when you release it, so people will know about it and they will not create another issue

**Comment by playground** [comment]
@manfredsteyer  Is the RC available for testing with cli 8?

**Comment by Timebutt** [comment]
I just installed the latest version you published with support for CLI 8, but I still seem to run into problems.

```
architect_1.createBuilder is not a function
TypeError: architect_1.createBuilder is not a function
    at Object.<anonymous> (/Users/nils.tijtgat/Showpad/Code/local-development/frontend/node_modules/ngx-build-plus/src/plus-dev-server/index.js:9:31)
```

These are the Angular packages I have installed right now:

```
Angular CLI: 8.0.0-rc.4
Node: 12.0.0
OS: darwin x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.7
@angular-devkit/build-angular      0.800.0-rc.4
@angular-devkit/build-ng-packagr   0.800.0-rc.4
@angular-devkit/build-optimizer    0.800.0-rc.4
@angular-devkit/build-webpack      0.13.7
@angular-devkit/core               8.0.0-rc.4
@angular-devkit/schematics         8.0.0-rc.4
@angular/cdk                       8.0.0-beta.2
@angular/http                      8.0.0-beta.10
@angular/material                  8.0.0-rc.1
@angular/pwa                       0.13.8
@ngtools/webpack                   8.0.0-rc.4
@schematics/angular                7.3.8
@schematics/update                 0.800.0-rc.4
rxjs                               6.5.1
typescript                         3.4.5
webpack                            4.29.0
```

Am I missing something, or is something else wrong?

**Comment by jmesa-sistel** [comment]
@Timebutt I have tested 8.0.0-rc.3.0.1 and works for me

**Comment by Timebutt** [comment]
Ok thanks for the feedback, I'll test again and see where it fails for me.

**Comment by Timebutt** [comment]
Ok, diving into the code I found out I needed to manually add `@angular-devkit/architect` as a dependency, shouldn't this be a peer dependency of `ngx-build-plus`?

Running the `ng serve` command again, I got this error:

```
Cannot find builder "ngx-build-plus:build".
Error: Cannot find builder "ngx-build-plus:build".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:45:19)
```

Following through the code again, it seems the `architect` is looking for the `build` builder in [`builders.json`](https://github.com/manfredsteyer/ngx-build-plus/blob/master/lib/builders.json), but there is no such builder there (only `browser`, `dev-server` and `karma`), so I'm guessing some configuration still isn't right. Will keep you posted.

**Comment by jmesa-sistel** [comment]
@Timebutt Thks for confirming. 
Not sure if I should close issue yet. If I close it people will not know that there is a 8.0.0-rc.3.0.1 version, I think I'll wait until @manfredsteyer make it official in the readme.

**Comment by Timebutt** [comment]
Ok that makes sense!

**Comment by bterriervm** [comment]
I also had to add `@angular-devkit/architect` explicitly and change from `build` to `browser`.

However now I have another error:
```
builderHandler is not a function
TypeError: builderHandler is not a function
    at Object.runBuilderHandler (...\node_modules\ngx-build-plus\src\utils\index.js:18:33)
    at buildWebpackBrowserPlus (...\node_modules\ngx-build-plus\src\browser\index.js:7:20)
```

I opened issue #100 for this specific error.

**Comment by playground** [comment]
@Timebutt how did you get it to work?  I kept getting these errors

```
ng add ngx-build-plus@latest --project element-two
Your global Angular CLI version (8.0.0-rc.4) is greater than your local
version (8.0.0-rc.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Installing packages for tooling via npm.
+ ngx-build-plus@8.0.0-rc.3.0.1
added 2 packages from 6 contributors and audited 22452 packages in 5.066s
found 0 vulnerabilities

Installed packages for tooling via npm.
Cannot find module '/angular-element-ivy/node_modules/ngx-build-plus/package.json'
Error: Cannot find module '/angular-element-ivy/node_modules/ngx-build-plus/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at NodeModulesEngineHost._resolveCollectionPath (/angular-element-ivy/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:74:39)
    at NodeModulesEngineHost.createCollectionDescription (/angular-element-ivy/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (/angular-element-ivy/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/angular-element-ivy/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at AddCommand.getCollection (/angular-element-ivy/node_modules/@angular/cli/models/schematic-command.js:128:35)
    at AddCommand.runSchematic (/angular-element-ivy/node_modules/@angular/cli/models/schematic-command.js:306:50)
    at AddCommand.executeSchematic (/angular-element-ivy/node_modules/@angular/cli/commands/add-impl.js:142:31)
    at AddCommand.run (/angular-element-ivy/node_modules/@angular/cli/commands/add-impl.js:106:21)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

```

**Comment by jmesa-sistel** [comment]
Closing because version 8.x is out

**Comment by pppdns** [comment]
I had the same issue:
`architect_1.createBuilder is not a function`

I don't know what fixed it exactly in my case but I removed and installed `@angular/cli` and then deleted `node_modules` completely and installed the dependencies again to have a clean state. It worked for me.

```
npm uninstall -g @angular/cli
npm install -g @angular/cli
```

**Comment by ChrisGibb** [comment]
After following all the advice above, which got me some way further, the last trick for me was to go through the versions on [this page](https://github.com/angular/angular-cli/releases) (specifically the 8.1.0 release) and comparing all the dependency version with my package.json.

The one that solved it for me was:

```
npm install @angular-devkit/build-angular@0.801.0
```

Now i'm up and running

**Comment by danieldanielecki** [comment]
Was able to fix `architect_1.createBuilder is not a function` by running:

```
npm i @angular-devkit/architect@latest
@angular-devkit/build-angular@latest
@angular-devkit/core@latest
@angular-devkit/schematics@latest
```

Taken from [this document](https://docs.google.com/document/d/1QOpQeDifPSg6F9WycDLcbQnpqjN96ew-Ap0_CB7CcCQ/edit).
